# Import and optimization

In [1]:
!pip install missingno phik boule osfclient cartopy pygeodesy

Requirement already satisfied: missingno in c:\programdata\anaconda3\envs\ds\lib\site-packages (0.5.2)
Requirement already satisfied: phik in c:\programdata\anaconda3\envs\ds\lib\site-packages (0.12.3)
Requirement already satisfied: boule in c:\programdata\anaconda3\envs\ds\lib\site-packages (0.5.0)
Requirement already satisfied: osfclient in c:\programdata\anaconda3\envs\ds\lib\site-packages (0.0.5)
Requirement already satisfied: cartopy in c:\programdata\anaconda3\envs\ds\lib\site-packages (0.23.0)
Requirement already satisfied: pygeodesy in c:\programdata\anaconda3\envs\ds\lib\site-packages (25.5.28)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\ds\lib\site-packages (from missingno) (1.26.4)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\ds\lib\site-packages (from missingno) (3.8.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\envs\ds\lib\site-packages (from missingno) (1.13.1)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\envs\ds\lib\site-packages (from missingno) (0.13.2)
Requirement already satisfied: pandas>=0.25.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from phik) (2.2.3)
Requirement already satisfied: joblib>=0.14.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from phik) (1.4.2)
Requirement already satisfied: attrs>=19.3.0 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from boule) (23.1.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\envs\ds\lib\site-packages (from osfclient) (2.32.3)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\envs\ds\lib\site-packages (from osfclient) (4.66.5)
Requirement already satisfied: six in c:\programdata\anaconda3\envs\ds\lib\site-packages (from osfclient) (1.16.0)
Requirement already satisfied: shapely>=1.7 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from cartopy) (2.0.7)
Requirement already satisfied: packaging>=20 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from cartopy) (24.1)
Requirement already satisfied: pyshp>=2.3 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from cartopy) (2.3.1)
Requirement already satisfied: pyproj>=3.3.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from cartopy) (3.6.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from matplotlib->missingno) (6.4.0)
Requirement already satisfied: zipp>=3.1.0 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from importlib-resources>=3.2.0->matplotlib->missingno) (3.19.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from pandas>=0.25.1->phik) (2022.7.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from pandas>=0.25.1->phik) (2023.3)
Requirement already satisfied: certifi in c:\programdata\anaconda3\envs\ds\lib\site-packages (from pyproj>=3.3.1->cartopy) (2025.6.15)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from requests->osfclient) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from requests->osfclient) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\envs\ds\lib\site-packages (from requests->osfclient) (1.26.20)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\ds\lib\site-packages (from tqdm->osfclient) (0.4.6)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# !osf -p  8zvwm clone

In [3]:
# import urllib.request
# url = 'https://sourceforge.net/projects/geographiclib/files/geoids-distrib/egm2008-1.tar.bz2'
# filename = 'Data/egm2008-1.tar.bz2'
# urllib.request.urlretrieve(url, filename)

In [4]:
# ! tar  -xvf  Data/egm2008-1.tar.bz2

In [5]:
import pandas as pd
import numpy as np
import math

import seaborn as sns
import missingno
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor
import plotly.express as px
import phik
from pygeodesy import GeoidKarney, LatLon_

from sklearn.model_selection import train_test_split

In [6]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
class CFG:
    TARGET = ['GGFM_f','D_phi']
    N_FOLDS = 5
    RANDOM_STATE = 3

    COLORADO_PATH = './Data/Synt/Colorado_600_merge.csv'
    NSO_PATH = './Data/Synt/NSO_600_merge.csv'

In [8]:
class DataLoader:
    def __init__(self, colorado: pd.DataFrame, nso: pd.DataFrame):
        self.colorado = colorado
        self.nso = nso
        self.log_features = []  # Список признаков для трансформации
        self.X = None
        self.y = None
    

    @staticmethod
    def reduce_mem_usage(dataframe):
        """ 
        Уменьшает использование памяти dataframe путем преобразования типов данных
        с автоматическим пропуском временных столбцов
        """
        start_mem = dataframe.memory_usage().sum() / 1024**2
        print(f"Изначальное использование памяти: {start_mem:.2f} MB")
        
        for col in dataframe.columns:
            col_type = dataframe[col].dtype
            
            # Пропускаем временные столбцы и категориальные данные
            if str(col_type).startswith('datetime') or str(col_type) == 'category':
                continue
                
            if col_type != object:
                c_min = dataframe[col].min()
                c_max = dataframe[col].max()
                
                if str(col_type)[:3] == 'int':
                    if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                        dataframe[col] = dataframe[col].astype(np.int8)
                    elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                        dataframe[col] = dataframe[col].astype(np.int16)
                    elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                        dataframe[col] = dataframe[col].astype(np.int32)
                    elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                        dataframe[col] = dataframe[col].astype(np.int64)
                else:
                    if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                        dataframe[col] = dataframe[col].astype(np.float16)
                    elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                        dataframe[col] = dataframe[col].astype(np.float32)
                    else:
                        dataframe[col] = dataframe[col].astype(np.float64)
            else:
                # Оптимизация строковых столбцов
                dataframe[col] = dataframe[col].astype('category')
        
        end_mem = dataframe.memory_usage().sum() / 1024**2
        print(f"Итоговое использование памяти: {end_mem:.2f} MB")
        print(f"Экономия {(start_mem - end_mem) / start_mem * 100:.1f}%")
        
        return dataframe


    def load(self, option='colorado'):
        print(f'Loading data')
        print(f'Choosed option:{option}')

        if option == 'compare':
            self.colorado = self.colorado.merge(self.nso, left_on='latitude(deg)', right_on='lat(deg)', how='outer')
        elif option == 'colorado':
            pass

        self.colorado = self.reduce_mem_usage(self.colorado)

In [9]:
class DataAnalysis:

    @staticmethod
    def info_df(df: pd.DataFrame) -> None:
        print('------------------------------')
        print('| Dataset information |')
        print('------------------------------')
        df.info()
        print('-----------------------------------------')
        print('| First 5 rows |')
        print('-----------------------------------------')
        display(df.head())
        print('--------------------')
        print('| Sum of duplicates |')
        print('--------------------')
        print(df.duplicated().sum())


    @staticmethod
    def view_distribution(data: pd.DataFrame, object_col = False, numeric_col = False) -> None:
        numeric_cols = data.select_dtypes(exclude=['object', 'datetime']).columns.to_list()
        object_cols = data.select_dtypes(include=['object']).columns.to_list()
        
        if numeric_col:
            fig, axes = plt.subplots(nrows=len(data[numeric_cols].columns), ncols=2, figsize=(len(numeric_cols)+15,len(numeric_cols)+7))
            j = 0
            for i in data[numeric_cols].columns:
                sns.histplot(data[numeric_cols][i], ax=axes[j, 0], kde=True, bins=40, edgecolor='black')
                axes[j, 0].set_title(i, fontsize=14)
                axes[j, 0].set_xlabel('')

                sns.boxplot(x=data[numeric_cols][i], ax=axes[j, 1], orient='h', palette='pink')
                axes[j, 1].set_title(i, fontsize=14)
                axes[j, 1].set_xlabel('')
                j += 1
            plt.suptitle(f'Num features\n\n', ha='center', fontweight='bold', fontsize=20);
            plt.tight_layout();
            plt.show();

        if object_col:
            _,ax = plt.subplots(len(object_cols),1, figsize=(len(object_cols)+7,len(object_cols)+20));
            ax =ax.flatten();
            g = 0
            for k in data[object_cols].columns:
                sns.countplot(data=data, x=k,ax=ax[g]);
                ax[g].set_xticklabels(labels=ax[g].get_xticklabels());
                ax[g].set_title(k);
                ax[g].set_xlabel('');
                g += 1
            plt.suptitle(f'Categorical\n\n', ha='center', fontweight='bold', fontsize=20);
            plt.show();


    @staticmethod
    def bloating_of_variance(data: pd.DataFrame) -> None:
        num = data.select_dtypes(exclude=['object', 'datetime']).columns.to_list()
        vif_data = pd.DataFrame()
        vif_data['feature'] = data.select_dtypes(exclude=['object', 'datetime']).columns.to_list()

        vif_data['VIF'] = [variance_inflation_factor(data[num].values, i) \
                                for i in range(len(data[num].columns))]
        print(vif_data)
    
    @staticmethod
    def balance_of_target(data: pd.DataFrame, target: str) -> None:
        sns.countplot(y=target, data=data, color='green', width=0.6);

    @staticmethod
    def plot_count(df: pd.core.frame.DataFrame, col: str, title_name: str='Train') -> None:
        # Set background color
        f, ax = plt.subplots(1, 2, figsize=(16, 7))
        plt.subplots_adjust(wspace=0.2)

        s1 = df[col].value_counts()
        N = len(s1)

        outer_sizes = s1
        inner_sizes = s1/N

        colors = sns.color_palette("mako")
        # hex_colors = [matplotlib.colors.to_hex(color) for color in colors]
        # print(hex_colors)
        
        outer_colors = ['#2e1e3b', '#413d7b', '#37659e', '#348fa7', '#40b7ad', '#8bdab2']
        inner_colors = ['#2e1e3b', '#413d7b', '#37659e', '#348fa7', '#40b7ad', '#8bdab2']
        #inner_colors = ['#59b3a3',] #'#433C64']

        ax[0].pie(
            outer_sizes,colors=outer_colors, 
            labels=s1.index.tolist(), 
            startangle=90, frame=True, radius=1.3, 
            explode=([0.05]*(N-1) + [.3]),
            wedgeprops={'linewidth' : 1, 'edgecolor' : 'black'}, 
            textprops={'fontsize': 12, 'weight': 'bold', 'color': 'white'}
        )

        textprops = {
            'size': 13, 
            'weight': 'bold', 
            'color': 'white'
        }

        ax[0].pie(
            inner_sizes, colors=inner_colors,
            radius=1, startangle=90,
            autopct='%1.f%%', explode=([.1]*(N-1) + [.3]),
            pctdistance=0.8, textprops=textprops
        )

        center_circle = plt.Circle((0,0), .68, color='black', fc='#243139', linewidth=0)
        ax[0].add_artist(center_circle)

        x = s1
        y = s1.index.tolist()
        sns.barplot(
            x=x, y=y, ax=ax[1],
            palette=colors, orient='horizontal'
        )

        ax[1].spines['top'].set_visible(False)
        ax[1].spines['right'].set_visible(False)
        ax[1].tick_params(
            axis='x',         
            which='both',      
            bottom=False,       
            labelbottom=False
        )

        for i, v in enumerate(s1):
            ax[1].text(v, i+0.1, str(v), color='white', fontweight='bold', fontsize=12)

        plt.setp(ax[1].get_yticklabels(), fontweight="bold")
        plt.setp(ax[1].get_xticklabels(), fontweight="bold")
        ax[1].set_xlabel(col, fontweight="bold", color='white')
        ax[1].set_ylabel('count', fontweight="bold", color='white')

        f.suptitle(f'{title_name}', fontsize=14, fontweight='bold', color='white')
        plt.tight_layout() 
        plt.show()
    
    @staticmethod
    def summary(data: pd.DataFrame) -> None:
        data = data.select_dtypes(exclude=['object', 'datetime'])
        sum = pd.DataFrame(data.dtypes, columns=['dtypes'])
        sum['missing#'] = data.isna().sum()
        sum['missing%'] = (data.isna().sum())/len(data)
        sum['uniques'] = data.nunique().values
        sum['count'] = data.count().values
        sum['skew'] = data.skew().values
        return sum
    
    @staticmethod
    def correlations(data: pd.DataFrame) -> None:
        data = data.drop(columns=CFG.TARGET)
        plt.figure(figsize=(15, 13));
        # Generate a mask for the upper triangle
        mask_pir = np.triu(np.ones_like(data.corr(method='pearson'), dtype=bool));
        mask_spi = np.triu(np.ones_like(data.corr(method='spearman'), dtype=bool));
       
        # Set up the matplotlib figure
        f, ax = plt.subplots(figsize=(11, 9));

        # Generate a custom diverging colormap
        cmap = sns.diverging_palette(230, 20, as_cmap=True);
        plt.title('PIRSON')
        sns.heatmap(data.corr(method='pearson'), annot=True, mask=mask_pir, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5}, robust=True);
        plt.show();
        
        plt.figure(figsize=(15, 13));
        f, ax = plt.subplots(figsize=(11, 9));
        plt.title('SPEARMAN')
        sns.heatmap(data.corr(method='spearman'), annot=True, mask=mask_spi, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5}, robust=True)
        plt.show();

        plt.figure(figsize=(15, 13));
        f, ax = plt.subplots(figsize=(11, 9));
        
        interval_cols = data.select_dtypes(exclude='object').columns.to_list()
        phik_overview = data.phik_matrix(interval_cols=interval_cols)
        plt.title(r'$\phi_K$')
        corr = phik_overview.round(2)
        mask = np.triu(np.ones_like(corr, dtype=bool))
        sns.heatmap(corr, mask=mask, cmap='pink_r', vmax=.3, center=0,
                annot=True, fmt='.2f', square=True, linewidths=.5, cbar_kws={"shrink": .5})

        significance_overview  = data.significance_matrix(interval_cols=interval_cols)

        plt.figure(figsize=(15, 13));
        plt.title('Statistical significance')
        corr = significance_overview.round(2)
        mask = np.triu(np.ones_like(corr, dtype=bool))
        sns.heatmap(corr, mask=mask, cmap='pink_r', vmax=5, vmin=-5, center=0,
                annot=True, fmt='.2f', square=True, linewidths=.5, cbar_kws={"shrink": .5})

        plt.show()
    
    @staticmethod
    def blinks(data: pd.DataFrame) -> None:
        print('Data gaps')
        missingno.matrix(data)

In [10]:
loader = DataLoader(
    colorado=pd.read_csv(CFG.COLORADO_PATH,
                        skipinitialspace=True,
                        index_col='index'),
    nso=pd.read_csv(CFG.NSO_PATH,
                        skipinitialspace=True,
                        index_col='index'),
)

In [11]:
loader.load()

Loading data
Choosed option:colorado
Изначальное использование памяти: 0.46 MB
Итоговое использование памяти: 0.17 MB
Экономия 63.5%

In [12]:
loader.colorado.head()

,Latitude (deg),Longitude (deg),Height (m),Height relief (m),Height geoid (m),r (m),GGFM_f,GGFM_g,TGFM_f,TGFM_g,Density (kg/m^3),Density STD (kg/m^3)
index,,,,,,,,,,,,
0,35.0,250.0,1614.0,1638.0,-24.46875,6386785.5,62410340.0,9.773438,62393676.0,9.773438,2412.0,270.5
1,35.0,250.0,1814.0,1638.0,-24.46875,6386985.5,62408384.0,9.773438,62391724.0,9.773438,2412.0,270.5
2,35.0,250.0,2114.0,1638.0,-24.46875,6387285.5,62405452.0,9.773438,62388792.0,9.773438,2412.0,270.5
3,35.0,250.0,2614.0,1638.0,-24.46875,6387785.5,62400568.0,9.765625,62383908.0,9.765625,2412.0,270.5
4,35.0,250.0,4200.0,1638.0,-24.46875,6389372.0,62385076.0,9.765625,62368412.0,9.765625,2412.0,270.5

In [13]:
loader.colorado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4608 entries, 0 to 4607
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Latitude (deg)        4608 non-null   float16
 1   Longitude (deg)       4608 non-null   float16
 2   Height (m)            4608 non-null   float16
 3   Height relief (m)     4608 non-null   float16
 4   Height geoid (m)      4608 non-null   float16
 5   r (m)                 4608 non-null   float32
 6   GGFM_f                4608 non-null   float32
 7   GGFM_g                4608 non-null   float16
 8   TGFM_f                4608 non-null   float32
 9   TGFM_g                4608 non-null   float16
 10  Density (kg/m^3)      4608 non-null   float16
 11  Density STD (kg/m^3)  4608 non-null   float16
dtypes: float16(9), float32(3)
memory usage: 171.0 KB

In [14]:
# for data in [loader.colorado]:
#     DataAnalysis.info_df(data)
#     DataAnalysis.blinks(data)
#     DataAnalysis.view_distribution(data, numeric_col=True)
#     DataAnalysis.correlations(data)

In [15]:
DataAnalysis.summary(loader.colorado).style.background_gradient(cmap='Blues')

In [16]:
loader.colorado.describe().T\
            .style.bar(subset=['mean'], color=px.colors.qualitative.G10[2])\
            .background_gradient(subset=['std'], cmap='Blues')\
            .background_gradient(subset=['50%'], cmap='BuGn')

In [17]:
loader.colorado.drop(columns=['GGFM_g'], inplace=True)
loader.colorado.drop_duplicates(inplace=True)
loader.colorado.reset_index(drop=True, inplace=True)

# Features

In [18]:
# geoidinterpolator=GeoidKarney('geoids/egm2008-1.pgm')

In [19]:
# class Gravity:
#     def __init__(self):
#         pass


#     @staticmethod
#     def height_anomaly(B: float, L: float) -> float:
#         ll = LatLon_(latlonh=B, lon=L, wrap=True) # преобразование в формат библиотеки pygeodesy
#         h_anomaly = geoidinterpolator(ll)
#         return h_anomaly
    
    
#     @staticmethod
#     def gamma_mean(B: float, L: float, H: float) -> float:
#         # программа составлена по нормальным формулам для расчета силы тяжести, Огородова Л. В. "Высшая геодезия", 2006, стр 85, формула 3.65 и 3.74
#         # параметры нормальной земли взяты из приказа "Об утверждении геометрических и физических числовых геодезических параметров
#         # государственной геодезической системы координат 2011 года"
#         # gamma_e=978032.696 # ГСК-2011
#         # beta=0.00530243
#         # beta1=0.00000585

#         gamma_e=978032.67715 # GRS80
#         beta=0.005302440112
#         beta1=0.000004378
#         norm_gravity_gradient=0.3086
#         gamma_mean=gamma_e*(1-beta*np.sin(np.radians(B))**2-beta1*np.sin(2*np.radians(B))**2)-(H/2)*norm_gravity_gradient
#         return gamma_mean
    
#     def potential(g_mean: float, h_geodesy: float, B: float) -> float:

#         GM = 3986005E8
#         a = 6378137
#         b = 6356752.3141
#         w = 7292115E-11
#         E = math.sqrt(a**2 + b**2)

#         q = .5*((1+3*((h_geodesy**2)/E**2))*math.atan(E / h_geodesy) - 3* (h_geodesy/E))
#         q0 = .5*((1+3*((h_geodesy**2)/E**2))*math.atan(E / b) - 3* (b/E)) 

#         u_ellipsoid = ((GM) / E) * math.atan(E / h_geodesy) + .5*(w**2)*(a**2)*(q/q0)*((math.sin(B)**2) - 1/3) + .5*(w**2)*(h_geodesy**2 + E**2) * math.cos(B)**2

#         return -(g_mean) * h_geodesy + u_ellipsoid
    
#     def delta_h(lat: float, g_meas: float, g_mean: float):
#         sin_lat = np.sin(np.radians(lat))
#         gamma = (9.7803267715 * (1 + 0.00193185138639 * sin_lat**2) / np.sqrt(1 - 0.00669437999014 * sin_lat**2)) * 1e5
#         a = 6378137

#         return ((g_meas - g_mean) * a) / gamma

In [20]:
# df['H_anomaly'] = np.vectorize(Gravity.height_anomaly)(df['latitude(deg)'], df['longitude(deg)'])

In [21]:
# df['H_geodesy'] = df['orthometric height above MSL(m)'] + df['H_anomaly']

In [22]:
# df['gamma_mean'] = np.vectorize(Gravity.gamma_mean)(df['latitude(deg)'], df['longitude(deg)'],df['H_geodesy'])

In [23]:
# df['potential'] = np.vectorize(Gravity.potential)(df['gravity(mGal)'], df['H_geodesy'],np.radians(df['latitude(deg)']))

In [24]:
# df['delta_H'] =  np.vectorize(Gravity.delta_h)(df['latitude(deg)'], df['gravity(mGal)'], df['gamma_mean'])

In [25]:
# df['phi_0'] = 0.0

In [26]:
# df.head()

In [27]:
loader.colorado['D_phi'] = loader.colorado['Height geoid (m)'] - loader.colorado['Height relief (m)']

In [28]:
loader.colorado.head(2)

,Latitude (deg),Longitude (deg),Height (m),Height relief (m),Height geoid (m),r (m),GGFM_f,TGFM_f,TGFM_g,Density (kg/m^3),Density STD (kg/m^3),D_phi
0,35.0,250.0,1614.0,1638.0,-24.46875,6386785.5,62410340.0,62393676.0,9.773438,2412.0,270.5,-1662.0
1,35.0,250.0,1814.0,1638.0,-24.46875,6386985.5,62408384.0,62391724.0,9.773438,2412.0,270.5,-1662.0

In [29]:
features = loader.colorado.drop(columns=CFG.TARGET)
target = loader.colorado[CFG.TARGET]

# Keras

In [30]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import (
    Input, Dense, BatchNormalization, Concatenate, Dropout, LeakyReLU
)
from tensorflow.keras.regularizers import l1_l2
from sklearn.preprocessing import StandardScaler
import keras_tuner as kt

from tensorflow.keras.callbacks import (EarlyStopping, 
                                      ReduceLROnPlateau, 
                                      ModelCheckpoint,
                                      TensorBoard)
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

In [31]:
try:
    # Сначала попробуем с NCCL (по умолчанию)
    strategy = tf.distribute.MirroredStrategy()
    print("Используется стратегия MirroredStrategy с NCCL")
except RuntimeError:
    # Если NCCL не работает, попробуем HierarchicalCopyAllReduce
    strategy = tf.distribute.MirroredStrategy(
        cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
    print("Используется стратегия MirroredStrategy с HierarchicalCopyAllReduce")

# Решение 2: Убедимся, что TensorFlow собран с поддержкой NCCL
print("Доступные устройства:", tf.config.list_physical_devices())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
Используется стратегия MirroredStrategy с NCCL
Доступные устройства: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Используется стратегия MirroredStrategy с NCCL
Доступные устройства: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [32]:
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = scaler_X.fit_transform(features)
y_scaled = scaler_y.fit_transform(target)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2)

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Model

def create_dual_output_loss(df, gamma_col='gamma_mean', phi0_col='phi_0'):
    """Custom loss function with multi-GPU support"""
    gamma_ref = tf.constant(df[gamma_col].values, dtype=tf.float32)
    phi0_ref = tf.constant(df[phi0_col].values, dtype=tf.float32)
    
    def loss_function(y_true, y_pred):
        true_pot, true_dphi = y_true
        pred_pot, pred_dphi = y_pred
        
        mse_pot = tf.reduce_mean(tf.square(true_pot - pred_pot))
        mse_dphi = tf.reduce_mean(tf.square(true_dphi - pred_dphi))
        
        with tf.GradientTape(persistent=True) as tape_second_order:
            with tf.GradientTape() as tape_first_order:
                tape_first_order.watch(model.inputs)
                pred_total = model(model.inputs)[0]
            first_derivs = tape_first_order.gradient(pred_total, model.inputs)
            
            laplacian = 0.0
            for coord_idx in range(3):
                second_deriv = tape_second_order.gradient(
                    first_derivs[:, coord_idx], 
                    model.inputs
                )[:, coord_idx]
                laplacian += tf.where(
                    tf.math.is_finite(second_deriv), 
                    second_deriv, 
                    tf.zeros_like(second_deriv)
                )
        
        laplace_loss = tf.reduce_mean(tf.square(laplacian))
        phys_relation_loss = tf.reduce_mean(tf.square(pred_dphi - (pred_pot - phi0_ref)))
        
        total_loss = (0.7*mse_pot + 0.3*mse_dphi + 0.1*laplace_loss + 0.05*phys_relation_loss)
        return total_loss
    
    return loss_function

In [35]:
from tensorflow.keras.layers import Concatenate

def build_enhanced_model(hp):
    with strategy.scope():
        # Ваш код построения модели остается без изменений
        num_features = features.shape[1]
        inputs = Input(shape=(num_features,), name='input_features')
        
        x = BatchNormalization()(inputs) if hp.Boolean('input_batch_norm') else inputs
        
        spatial_features = x[:, :3]
        physical_features = x[:, 3:]
        
        # Spatial stream
        spatial_stream = spatial_features
        for i in range(hp.Int('spatial_layers', 1, 3)):
            units = hp.Int(f'spatial_units_{i}', 32, 256, 32)
            spatial_stream = Dense(units, activation='relu')(spatial_stream)
            if hp.Boolean(f'spatial_bn_{i}'):
                spatial_stream = BatchNormalization()(spatial_stream)
        
        # Physical stream
        physical_stream = physical_features
        for i in range(hp.Int('physical_layers', 1, 3)):
            units = hp.Int(f'physical_units_{i}', 32, 256, 32)
            physical_stream = Dense(units, activation='relu')(physical_stream)
            if hp.Boolean(f'physical_bn_{i}'):
                physical_stream = BatchNormalization()(physical_stream)
        
        merged = Concatenate()([spatial_stream, physical_stream])
        
        for i in range(hp.Int('joint_layers', 1, 3)):
            units = hp.Int(f'joint_units_{i}', 64, 512, 32)
            activation_choice = hp.Choice(f'activation_{i}', ['relu', 'tanh', 'leaky_relu', 'elu'])
            activation = LeakyReLU(alpha=0.1) if activation_choice == 'leaky_relu' else activation_choice
            
            merged = Dense(units, activation=activation)(merged)
            if hp.Boolean(f'joint_bn_{i}'):
                merged = BatchNormalization()(merged)
            
            if (dropout_rate := hp.Float(f'dropout_{i}', 0.0, 0.5, 0.1)) > 0:
                merged = Dropout(dropout_rate)(merged)
        
        output_pot = Dense(1, name='potential',
                         kernel_regularizer=l1_l2(
                             hp.Float('pot_l1', 0, 0.1),
                             hp.Float('pot_l2', 0, 0.1)))(merged)
        
        output_dh = Dense(1, name='delta_h',
                        kernel_regularizer=l1_l2(
                            hp.Float('dh_l1', 0, 0.1),
                            hp.Float('dh_l2', 0, 0.1)))(merged)
        
        model = Model(inputs, [output_pot, output_dh])
        
        # Решение 3: Используем оптимизатор, который точно работает с распределенным обучением
        optimizer = tf.keras.optimizers.legacy.Adam(
            hp.Float('lr', 1e-5, 1e-2, sampling='log'),
            clipvalue=hp.Float('clipvalue', 0.1, 1.0)
        )
        
        pot_weight = hp.Float('pot_weight', 0.1, 0.9)
        model.compile(
            optimizer=optimizer,
            loss={'potential': 'mse', 'delta_h': 'mse'},
            loss_weights=[pot_weight, 1.0 - pot_weight],
            metrics={'potential': ['mae', 'mse'], 'delta_h': ['mae', 'mse']}
        )
        
        return model

In [36]:
tuner = kt.Hyperband(
    build_enhanced_model,
    objective='val_loss',
    max_epochs=100,
    directory='enhanced_tuning_dir',
    project_name='enhanced_gravity_model',
    overwrite=True,
    factor=3,
    hyperband_iterations=2
)

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).

In [37]:
callbacks = [
    EarlyStopping(patience=10, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6)
]

# Решение 4: Уменьшим batch_size для первых попыток
initial_batch_size = 8  # Начинаем с меньшего размера

try:
    tuner.search(
        X_train, 
        {'potential': y_train[:, 0], 'delta_h': y_train[:, 1]},
        validation_data=(X_test, {'potential': y_test[:, 0], 'delta_h': y_test[:, 1]}),
        epochs=100,
        batch_size=initial_batch_size,
        callbacks=callbacks,
        verbose=2
    )
except Exception as e:
    print(f"Ошибка при обучении: {e}")
    print("Попробуйте следующие решения:")
    print("1. Установите TensorFlow с поддержкой NCCL: pip install tensorflow-gpu==2.10.0")
    print("2. Используйте только одну GPU, установив: os.environ['CUDA_VISIBLE_DEVICES'] = '0'")
    print("3. Попробуйте уменьшить batch_size еще больше")

Trial 196 Complete [00h 00m 31s]
val_loss: 0.04128391668200493

Best val_loss So Far: 0.005762014538049698
Total elapsed time: 00h 48m 51s

Search: Running Trial #197

Value             |Best Value So Far |Hyperparameter
True              |False             |input_batch_norm
3                 |2                 |spatial_layers
256               |32                |spatial_units_0
True              |True              |spatial_bn_0
1                 |1                 |physical_layers
64                |160               |physical_units_0
False             |False             |physical_bn_0
3                 |2                 |joint_layers
160               |352               |joint_units_0
relu              |elu               |activation_0
True              |False             |joint_bn_0
0.2               |0.2               |dropout_0
0.065291          |0.019786          |pot_l1
0.044165          |0.028501          |pot_l2
0.047649          |0.097614          |dh_l1
0.041175          |0.099096          |dh_l2
0.00027661        |0.0005141         |lr
0.69777           |0.54617           |clipvalue
0.75191           |0.22585           |pot_weight
128               |256               |spatial_units_1
True              |True              |spatial_bn_1
256               |192               |physical_units_1
False             |False             |physical_bn_1
384               |256               |joint_units_1
tanh              |leaky_relu        |activation_1
False             |False             |joint_bn_1
0.1               |0.2               |dropout_1
64                |128               |spatial_units_2
True              |True              |spatial_bn_2
96                |64                |physical_units_2
True              |False             |physical_bn_2
512               |448               |joint_units_2
leaky_relu        |elu               |activation_2
False             |True              |joint_bn_2
0.2               |0.1               |dropout_2
12                |100               |tuner/epochs
4                 |34                |tuner/initial_epoch
3                 |4                 |tuner/bracket
1                 |4                 |tuner/round
0173              |0143              |tuner/trial_id

Epoch 5/12
461/461 - 7s - loss: 0.2176 - potential_loss: 0.1370 - delta_h_loss: 0.2072 - potential_mae: 0.2936 - potential_mse: 0.1370 - delta_h_mae: 0.3521 - delta_h_mse: 0.2072 - val_loss: 0.1021 - val_potential_loss: 0.0375 - val_delta_h_loss: 0.0385 - val_potential_mae: 0.1554 - val_potential_mse: 0.0375 - val_delta_h_mae: 0.1487 - val_delta_h_mse: 0.0385 - lr: 2.7661e-04 - 7s/epoch - 14ms/step
Epoch 6/12
461/461 - 3s - loss: 0.2092 - potential_loss: 0.1362 - delta_h_loss: 0.1986 - potential_mae: 0.2905 - potential_mse: 0.1362 - delta_h_mae: 0.3434 - delta_h_mse: 0.1986 - val_loss: 0.0856 - val_potential_loss: 0.0367 - val_delta_h_loss: 0.0350 - val_potential_mae: 0.1431 - val_potential_mse: 0.0367 - val_delta_h_mae: 0.1368 - val_delta_h_mse: 0.0350 - lr: 2.7661e-04 - 3s/epoch - 8ms/step
Epoch 7/12
461/461 - 3s - loss: 0.1946 - potential_loss: 0.1279 - delta_h_loss: 0.1964 - potential_mae: 0.2805 - potential_mse: 0.1279 - delta_h_mae: 0.3421 - delta_h_mse: 0.1964 - val_loss: 0.0907 - val_potential_loss: 0.0402 - val_delta_h_loss: 0.0442 - val_potential_mae: 0.1646 - val_potential_mse: 0.0402 - val_delta_h_mae: 0.1468 - val_delta_h_mse: 0.0442 - lr: 2.7661e-04 - 3s/epoch - 7ms/step
Epoch 8/12
461/461 - 3s - loss: 0.1939 - potential_loss: 0.1269 - delta_h_loss: 0.2051 - potential_mae: 0.2792 - potential_mse: 0.1269 - delta_h_mae: 0.3459 - delta_h_mse: 0.2051 - val_loss: 0.0702 - val_potential_loss: 0.0220 - val_delta_h_loss: 0.0298 - val_potential_mae: 0.1101 - val_potential_mse: 0.0220 - val_delta_h_mae: 0.1308 - val_delta_h_mse: 0.0298 - lr: 2.7661e-04 - 3s/epoch - 7ms/step
Epoch 9/12

In [74]:
from tensorflow.keras.callbacks import (EarlyStopping, 
                                      ReduceLROnPlateau, 
                                      ModelCheckpoint,
                                      TensorBoard)

# Получаем лучшую модель
best_model = tuner.get_best_models(num_models=1)[0]

# Оптимальные callback'ы
callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=25,  # Большой patience для тщательного обучения
        restore_best_weights=True,
        mode='min',
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=10,  # Долгое ожидание перед уменьшением lr
        min_lr=1e-7,  # Очень маленький конечный learning rate
        verbose=1
    ),
    ModelCheckpoint(
        'best_gravity_model.h5',
        monitor='val_loss',
        save_best_only=True,
        save_weights_only=False,
        mode='min',
        verbose=1
    ),
    TensorBoard(
        log_dir='logs/final_training',
        histogram_freq=1,
        write_graph=True,
        write_images=True,
        update_freq='epoch'
    )
]

# Параметры обучения с максимальной точностью
history = best_model.fit(
    X_train,
    {'potential': y_train[:, 0], 'delta_h': y_train[:, 1]},
    validation_data=(X_test, {'potential': y_test[:, 0], 'delta_h': y_test[:, 1]}),
    epochs=1000,  # Очень большое число эпох (EarlyStopping остановит раньше)
    batch_size=16,  # Меньший batch size для лучшей точности
    callbacks=callbacks,
    verbose=2,
    shuffle=True,
    class_weight=None,
    sample_weight=None,
    initial_epoch=0,
    steps_per_epoch=None,
    validation_steps=None,
    validation_batch_size=None,
    validation_freq=1,
)

Epoch 1/1000

Epoch 1: val_loss improved from inf to 0.02850, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 2s - 9ms/step - delta_h_loss: 0.0056 - delta_h_mae: 0.0512 - delta_h_mse: 0.0056 - loss: 0.0313 - potential_loss: 0.0320 - potential_mae: 0.1339 - potential_mse: 0.0318 - val_delta_h_loss: 0.0069 - val_delta_h_mae: 0.0647 - val_delta_h_mse: 0.0069 - val_loss: 0.0285 - val_potential_loss: 0.0092 - val_potential_mae: 0.0801 - val_potential_mse: 0.0092 - learning_rate: 0.0017
Epoch 2/1000

Epoch 2: val_loss improved from 0.02850 to 0.02258, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0047 - delta_h_mae: 0.0516 - delta_h_mse: 0.0046 - loss: 0.0270 - potential_loss: 0.0246 - potential_mae: 0.1208 - potential_mse: 0.0246 - val_delta_h_loss: 0.0135 - val_delta_h_mae: 0.0889 - val_delta_h_mse: 0.0135 - val_loss: 0.0226 - val_potential_loss: 0.0043 - val_potential_mae: 0.0497 - val_potential_mse: 0.0043 - learning_rate: 0.0017
Epoch 3/1000

Epoch 3: val_loss improved from 0.02258 to 0.01420, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0053 - delta_h_mae: 0.0550 - delta_h_mse: 0.0053 - loss: 0.0263 - potential_loss: 0.0216 - potential_mae: 0.1126 - potential_mse: 0.0215 - val_delta_h_loss: 0.0028 - val_delta_h_mae: 0.0417 - val_delta_h_mse: 0.0028 - val_loss: 0.0142 - val_potential_loss: 0.0094 - val_potential_mae: 0.0812 - val_potential_mse: 0.0094 - learning_rate: 0.0017
Epoch 4/1000

Epoch 4: val_loss did not improve from 0.01420
231/231 - 1s - 2ms/step - delta_h_loss: 0.0044 - delta_h_mae: 0.0500 - delta_h_mse: 0.0044 - loss: 0.0250 - potential_loss: 0.0207 - potential_mae: 0.1082 - potential_mse: 0.0206 - val_delta_h_loss: 0.0084 - val_delta_h_mae: 0.0758 - val_delta_h_mse: 0.0084 - val_loss: 0.0323 - val_potential_loss: 0.0370 - val_potential_mae: 0.1590 - val_potential_mse: 0.0370 - learning_rate: 0.0017
Epoch 5/1000

Epoch 5: val_loss did not improve from 0.01420
231/231 - 1s - 3ms/step - delta_h_loss: 0.0058 - delta_h_mae: 0.0563 - delta_h_mse: 0.0058 - loss: 0.0271 - potential_loss: 0.0198 - potential_mae: 0.1060 - potential_mse: 0.0199 - val_delta_h_loss: 0.0088 - val_delta_h_mae: 0.0858 - val_delta_h_mse: 0.0088 - val_loss: 0.0249 - val_potential_loss: 0.0046 - val_potential_mae: 0.0537 - val_potential_mse: 0.0046 - learning_rate: 0.0017
Epoch 6/1000

Epoch 6: val_loss did not improve from 0.01420
231/231 - 1s - 3ms/step - delta_h_loss: 0.0051 - delta_h_mae: 0.0536 - delta_h_mse: 0.0051 - loss: 0.0239 - potential_loss: 0.0133 - potential_mae: 0.0898 - potential_mse: 0.0133 - val_delta_h_loss: 0.0047 - val_delta_h_mae: 0.0513 - val_delta_h_mse: 0.0047 - val_loss: 0.0266 - val_potential_loss: 0.0061 - val_potential_mae: 0.0620 - val_potential_mse: 0.0061 - learning_rate: 0.0017
Epoch 7/1000

Epoch 7: val_loss did not improve from 0.01420
231/231 - 1s - 2ms/step - delta_h_loss: 0.0060 - delta_h_mae: 0.0574 - delta_h_mse: 0.0060 - loss: 0.0242 - potential_loss: 0.0131 - potential_mae: 0.0884 - potential_mse: 0.0130 - val_delta_h_loss: 0.0013 - val_delta_h_mae: 0.0279 - val_delta_h_mse: 0.0013 - val_loss: 0.0224 - val_potential_loss: 0.0180 - val_potential_mae: 0.1065 - val_potential_mse: 0.0180 - learning_rate: 0.0017
Epoch 8/1000

Epoch 8: val_loss did not improve from 0.01420
231/231 - 1s - 2ms/step - delta_h_loss: 0.0040 - delta_h_mae: 0.0481 - delta_h_mse: 0.0040 - loss: 0.0232 - potential_loss: 0.0142 - potential_mae: 0.0909 - potential_mse: 0.0141 - val_delta_h_loss: 0.0013 - val_delta_h_mae: 0.0283 - val_delta_h_mse: 0.0013 - val_loss: 0.0221 - val_potential_loss: 0.0164 - val_potential_mae: 0.1000 - val_potential_mse: 0.0164 - learning_rate: 0.0017
Epoch 9/1000

Epoch 9: val_loss did not improve from 0.01420
231/231 - 1s - 3ms/step - delta_h_loss: 0.0046 - delta_h_mae: 0.0487 - delta_h_mse: 0.0046 - loss: 0.0241 - potential_loss: 0.0145 - potential_mae: 0.0910 - potential_mse: 0.0143 - val_delta_h_loss: 0.0018 - val_delta_h_mae: 0.0324 - val_delta_h_mse: 0.0018 - val_loss: 0.0176 - val_potential_loss: 0.0054 - val_potential_mae: 0.0574 - val_potential_mse: 0.0055 - learning_rate: 0.0017
Epoch 10/1000

Epoch 10: val_loss did not improve from 0.01420
231/231 - 1s - 3ms/step - delta_h_loss: 0.0036 - delta_h_mae: 0.0448 - delta_h_mse: 0.0036 - loss: 0.0229 - potential_loss: 0.0139 - potential_mae: 0.0879 - potential_mse: 0.0139 - val_delta_h_loss: 0.0018 - val_delta_h_mae: 0.0336 - val_delta_h_mse: 0.0018 - val_loss: 0.0191 - val_potential_loss: 0.0112 - val_potential_mae: 0.0866 - val_potential_mse: 0.0113 - learning_rate: 0.0017
Epoch 11/1000

Epoch 11: val_loss did not improve from 0.01420
231/231 - 1s - 2ms/step - delta_h_loss: 0.0037 - delta_h_mae: 0.0453 - delta_h_mse: 0.0037 - loss: 0.0226 - potential_loss: 0.0093 - potential_mae: 0.0760 - potential_mse: 0.0094 - val_delta_h_loss: 5.4420e-04 - val_delta_h_mae: 0.0182 - val_delta_h_mse: 5.4673e-04 - val_loss: 0.0198 - val_potential_loss: 0.0055 - val_potential_mae: 0.0588 - val_potential_mse: 0.0054 - learning_rate: 0.0017
Epoch 12/1000

Epoch 12: val_loss did not improve from 0.01420
231/231 - 1s - 3ms/step - delta_h_loss: 0.0034 - delta_h_mae: 0.0427 - delta_h_mse: 0.0034 - loss: 0.0220 - potential_loss: 0.0101 - potential_mae: 0.0787 - potential_mse: 0.0101 - val_delta_h_loss: 0.0015 - val_delta_h_mae: 0.0313 - val_delta_h_mse: 0.0015 - val_loss: 0.0263 - val_potential_loss: 0.0122 - val_potential_mae: 0.0888 - val_potential_mse: 0.0123 - learning_rate: 0.0017
Epoch 13/1000

Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0008259725291281939.

Epoch 13: val_loss did not improve from 0.01420
231/231 - 1s - 2ms/step - delta_h_loss: 0.0054 - delta_h_mae: 0.0549 - delta_h_mse: 0.0055 - loss: 0.0245 - potential_loss: 0.0089 - potential_mae: 0.0727 - potential_mse: 0.0089 - val_delta_h_loss: 0.0014 - val_delta_h_mae: 0.0296 - val_delta_h_mse: 0.0014 - val_loss: 0.0194 - val_potential_loss: 0.0045 - val_potential_mae: 0.0538 - val_potential_mse: 0.0045 - learning_rate: 0.0017
Epoch 14/1000

Epoch 14: val_loss improved from 0.01420 to 0.01239, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0015 - delta_h_mae: 0.0291 - delta_h_mse: 0.0015 - loss: 0.0137 - potential_loss: 0.0050 - potential_mae: 0.0545 - potential_mse: 0.0049 - val_delta_h_loss: 3.9079e-04 - val_delta_h_mae: 0.0154 - val_delta_h_mse: 3.9027e-04 - val_loss: 0.0124 - val_potential_loss: 0.0037 - val_potential_mae: 0.0471 - val_potential_mse: 0.0037 - learning_rate: 8.2597e-04
Epoch 15/1000

Epoch 15: val_loss did not improve from 0.01239
231/231 - 1s - 2ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0276 - delta_h_mse: 0.0013 - loss: 0.0126 - potential_loss: 0.0054 - potential_mae: 0.0558 - potential_mse: 0.0054 - val_delta_h_loss: 0.0012 - val_delta_h_mae: 0.0288 - val_delta_h_mse: 0.0012 - val_loss: 0.0165 - val_potential_loss: 0.0165 - val_potential_mae: 0.1049 - val_potential_mse: 0.0165 - learning_rate: 8.2597e-04
Epoch 16/1000

Epoch 16: val_loss did not improve from 0.01239
231/231 - 1s - 2ms/step - delta_h_loss: 0.0021 - delta_h_mae: 0.0352 - delta_h_mse: 0.0022 - loss: 0.0130 - potential_loss: 0.0060 - potential_mae: 0.0596 - potential_mse: 0.0060 - val_delta_h_loss: 7.0792e-04 - val_delta_h_mae: 0.0210 - val_delta_h_mse: 7.0542e-04 - val_loss: 0.0141 - val_potential_loss: 0.0093 - val_potential_mae: 0.0803 - val_potential_mse: 0.0093 - learning_rate: 8.2597e-04
Epoch 17/1000

Epoch 17: val_loss improved from 0.01239 to 0.01216, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 2ms/step - delta_h_loss: 0.0022 - delta_h_mae: 0.0358 - delta_h_mse: 0.0022 - loss: 0.0130 - potential_loss: 0.0065 - potential_mae: 0.0599 - potential_mse: 0.0064 - val_delta_h_loss: 0.0020 - val_delta_h_mae: 0.0354 - val_delta_h_mse: 0.0020 - val_loss: 0.0122 - val_potential_loss: 0.0079 - val_potential_mae: 0.0679 - val_potential_mse: 0.0079 - learning_rate: 8.2597e-04
Epoch 18/1000

Epoch 18: val_loss did not improve from 0.01216
231/231 - 1s - 2ms/step - delta_h_loss: 0.0022 - delta_h_mae: 0.0332 - delta_h_mse: 0.0022 - loss: 0.0126 - potential_loss: 0.0057 - potential_mae: 0.0570 - potential_mse: 0.0056 - val_delta_h_loss: 0.0016 - val_delta_h_mae: 0.0287 - val_delta_h_mse: 0.0017 - val_loss: 0.0132 - val_potential_loss: 0.0036 - val_potential_mae: 0.0482 - val_potential_mse: 0.0036 - learning_rate: 8.2597e-04
Epoch 19/1000

Epoch 19: val_loss improved from 0.01216 to 0.01127, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 2ms/step - delta_h_loss: 0.0019 - delta_h_mae: 0.0321 - delta_h_mse: 0.0019 - loss: 0.0122 - potential_loss: 0.0038 - potential_mae: 0.0472 - potential_mse: 0.0038 - val_delta_h_loss: 0.0012 - val_delta_h_mae: 0.0279 - val_delta_h_mse: 0.0012 - val_loss: 0.0113 - val_potential_loss: 0.0034 - val_potential_mae: 0.0430 - val_potential_mse: 0.0034 - learning_rate: 8.2597e-04
Epoch 20/1000

Epoch 20: val_loss did not improve from 0.01127
231/231 - 1s - 3ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0266 - delta_h_mse: 0.0013 - loss: 0.0114 - potential_loss: 0.0040 - potential_mae: 0.0491 - potential_mse: 0.0040 - val_delta_h_loss: 5.8323e-04 - val_delta_h_mae: 0.0191 - val_delta_h_mse: 5.8133e-04 - val_loss: 0.0130 - val_potential_loss: 0.0087 - val_potential_mae: 0.0707 - val_potential_mse: 0.0087 - learning_rate: 8.2597e-04
Epoch 21/1000

Epoch 21: val_loss improved from 0.01127 to 0.01033, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0021 - delta_h_mae: 0.0347 - delta_h_mse: 0.0021 - loss: 0.0125 - potential_loss: 0.0059 - potential_mae: 0.0595 - potential_mse: 0.0059 - val_delta_h_loss: 0.0016 - val_delta_h_mae: 0.0322 - val_delta_h_mse: 0.0016 - val_loss: 0.0103 - val_potential_loss: 0.0011 - val_potential_mae: 0.0270 - val_potential_mse: 0.0011 - learning_rate: 8.2597e-04
Epoch 22/1000

Epoch 22: val_loss improved from 0.01033 to 0.01020, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0011 - delta_h_mae: 0.0249 - delta_h_mse: 0.0011 - loss: 0.0111 - potential_loss: 0.0040 - potential_mae: 0.0481 - potential_mse: 0.0040 - val_delta_h_loss: 6.2589e-04 - val_delta_h_mae: 0.0196 - val_delta_h_mse: 6.2670e-04 - val_loss: 0.0102 - val_potential_loss: 0.0022 - val_potential_mae: 0.0369 - val_potential_mse: 0.0022 - learning_rate: 8.2597e-04
Epoch 23/1000

Epoch 23: val_loss did not improve from 0.01020
231/231 - 1s - 2ms/step - delta_h_loss: 0.0016 - delta_h_mae: 0.0295 - delta_h_mse: 0.0016 - loss: 0.0118 - potential_loss: 0.0049 - potential_mae: 0.0538 - potential_mse: 0.0049 - val_delta_h_loss: 0.0011 - val_delta_h_mae: 0.0249 - val_delta_h_mse: 0.0011 - val_loss: 0.0113 - val_potential_loss: 0.0020 - val_potential_mae: 0.0338 - val_potential_mse: 0.0020 - learning_rate: 8.2597e-04
Epoch 24/1000

Epoch 24: val_loss did not improve from 0.01020
231/231 - 1s - 2ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0267 - delta_h_mse: 0.0013 - loss: 0.0111 - potential_loss: 0.0036 - potential_mae: 0.0463 - potential_mse: 0.0036 - val_delta_h_loss: 0.0017 - val_delta_h_mae: 0.0332 - val_delta_h_mse: 0.0017 - val_loss: 0.0110 - val_potential_loss: 0.0032 - val_potential_mae: 0.0462 - val_potential_mse: 0.0032 - learning_rate: 8.2597e-04
Epoch 25/1000

Epoch 25: val_loss did not improve from 0.01020
231/231 - 1s - 3ms/step - delta_h_loss: 0.0018 - delta_h_mae: 0.0309 - delta_h_mse: 0.0018 - loss: 0.0116 - potential_loss: 0.0043 - potential_mae: 0.0504 - potential_mse: 0.0043 - val_delta_h_loss: 8.7558e-04 - val_delta_h_mae: 0.0231 - val_delta_h_mse: 8.7314e-04 - val_loss: 0.0103 - val_potential_loss: 0.0059 - val_potential_mae: 0.0583 - val_potential_mse: 0.0059 - learning_rate: 8.2597e-04
Epoch 26/1000

Epoch 26: val_loss did not improve from 0.01020
231/231 - 1s - 2ms/step - delta_h_loss: 0.0014 - delta_h_mae: 0.0282 - delta_h_mse: 0.0014 - loss: 0.0115 - potential_loss: 0.0046 - potential_mae: 0.0518 - potential_mse: 0.0046 - val_delta_h_loss: 0.0012 - val_delta_h_mae: 0.0255 - val_delta_h_mse: 0.0012 - val_loss: 0.0108 - val_potential_loss: 0.0014 - val_potential_mae: 0.0289 - val_potential_mse: 0.0014 - learning_rate: 8.2597e-04
Epoch 27/1000

Epoch 27: val_loss improved from 0.01020 to 0.00981, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 8.5001e-04 - delta_h_mae: 0.0231 - delta_h_mse: 8.5193e-04 - loss: 0.0106 - potential_loss: 0.0031 - potential_mae: 0.0434 - potential_mse: 0.0031 - val_delta_h_loss: 1.9099e-04 - val_delta_h_mae: 0.0104 - val_delta_h_mse: 1.9153e-04 - val_loss: 0.0098 - val_potential_loss: 0.0013 - val_potential_mae: 0.0287 - val_potential_mse: 0.0013 - learning_rate: 8.2597e-04
Epoch 28/1000

Epoch 28: val_loss did not improve from 0.00981
231/231 - 1s - 2ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0264 - delta_h_mse: 0.0013 - loss: 0.0112 - potential_loss: 0.0039 - potential_mae: 0.0484 - potential_mse: 0.0039 - val_delta_h_loss: 0.0043 - val_delta_h_mae: 0.0536 - val_delta_h_mse: 0.0042 - val_loss: 0.0132 - val_potential_loss: 0.0024 - val_potential_mae: 0.0355 - val_potential_mse: 0.0024 - learning_rate: 8.2597e-04
Epoch 29/1000

Epoch 29: val_loss improved from 0.00981 to 0.00934, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0266 - delta_h_mse: 0.0013 - loss: 0.0113 - potential_loss: 0.0028 - potential_mae: 0.0411 - potential_mse: 0.0028 - val_delta_h_loss: 6.5071e-04 - val_delta_h_mae: 0.0207 - val_delta_h_mse: 6.5196e-04 - val_loss: 0.0093 - val_potential_loss: 0.0013 - val_potential_mae: 0.0296 - val_potential_mse: 0.0013 - learning_rate: 8.2597e-04
Epoch 30/1000

Epoch 30: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0015 - delta_h_mae: 0.0290 - delta_h_mse: 0.0015 - loss: 0.0112 - potential_loss: 0.0026 - potential_mae: 0.0394 - potential_mse: 0.0026 - val_delta_h_loss: 0.0012 - val_delta_h_mae: 0.0276 - val_delta_h_mse: 0.0012 - val_loss: 0.0116 - val_potential_loss: 0.0035 - val_potential_mae: 0.0465 - val_potential_mse: 0.0035 - learning_rate: 8.2597e-04
Epoch 31/1000

Epoch 31: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0015 - delta_h_mae: 0.0289 - delta_h_mse: 0.0015 - loss: 0.0118 - potential_loss: 0.0036 - potential_mae: 0.0467 - potential_mse: 0.0036 - val_delta_h_loss: 5.2532e-04 - val_delta_h_mae: 0.0184 - val_delta_h_mse: 5.2619e-04 - val_loss: 0.0107 - val_potential_loss: 0.0011 - val_potential_mae: 0.0260 - val_potential_mse: 0.0011 - learning_rate: 8.2597e-04
Epoch 32/1000

Epoch 32: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0020 - delta_h_mae: 0.0336 - delta_h_mse: 0.0020 - loss: 0.0120 - potential_loss: 0.0032 - potential_mae: 0.0438 - potential_mse: 0.0032 - val_delta_h_loss: 5.5172e-04 - val_delta_h_mae: 0.0176 - val_delta_h_mse: 5.5054e-04 - val_loss: 0.0120 - val_potential_loss: 0.0049 - val_potential_mae: 0.0558 - val_potential_mse: 0.0049 - learning_rate: 8.2597e-04
Epoch 33/1000

Epoch 33: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0017 - delta_h_mae: 0.0310 - delta_h_mse: 0.0017 - loss: 0.0117 - potential_loss: 0.0029 - potential_mae: 0.0419 - potential_mse: 0.0029 - val_delta_h_loss: 0.0021 - val_delta_h_mae: 0.0365 - val_delta_h_mse: 0.0021 - val_loss: 0.0108 - val_potential_loss: 0.0023 - val_potential_mae: 0.0420 - val_potential_mse: 0.0023 - learning_rate: 8.2597e-04
Epoch 34/1000

Epoch 34: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0017 - delta_h_mae: 0.0308 - delta_h_mse: 0.0017 - loss: 0.0117 - potential_loss: 0.0034 - potential_mae: 0.0454 - potential_mse: 0.0034 - val_delta_h_loss: 7.5028e-04 - val_delta_h_mae: 0.0219 - val_delta_h_mse: 7.5254e-04 - val_loss: 0.0121 - val_potential_loss: 0.0037 - val_potential_mae: 0.0498 - val_potential_mse: 0.0037 - learning_rate: 8.2597e-04
Epoch 35/1000

Epoch 35: val_loss did not improve from 0.00934
231/231 - 1s - 2ms/step - delta_h_loss: 0.0030 - delta_h_mae: 0.0411 - delta_h_mse: 0.0030 - loss: 0.0129 - potential_loss: 0.0033 - potential_mae: 0.0433 - potential_mse: 0.0033 - val_delta_h_loss: 0.0021 - val_delta_h_mae: 0.0369 - val_delta_h_mse: 0.0021 - val_loss: 0.0123 - val_potential_loss: 0.0012 - val_potential_mae: 0.0287 - val_potential_mse: 0.0012 - learning_rate: 8.2597e-04
Epoch 36/1000

Epoch 36: val_loss did not improve from 0.00934
231/231 - 1s - 2ms/step - delta_h_loss: 0.0035 - delta_h_mae: 0.0449 - delta_h_mse: 0.0035 - loss: 0.0144 - potential_loss: 0.0047 - potential_mae: 0.0520 - potential_mse: 0.0047 - val_delta_h_loss: 0.0131 - val_delta_h_mae: 0.0946 - val_delta_h_mse: 0.0131 - val_loss: 0.0226 - val_potential_loss: 0.0081 - val_potential_mae: 0.0644 - val_potential_mse: 0.0081 - learning_rate: 8.2597e-04
Epoch 37/1000

Epoch 37: val_loss did not improve from 0.00934
231/231 - 1s - 2ms/step - delta_h_loss: 0.0022 - delta_h_mae: 0.0350 - delta_h_mse: 0.0022 - loss: 0.0131 - potential_loss: 0.0025 - potential_mae: 0.0384 - potential_mse: 0.0025 - val_delta_h_loss: 0.0016 - val_delta_h_mae: 0.0339 - val_delta_h_mse: 0.0017 - val_loss: 0.0131 - val_potential_loss: 0.0079 - val_potential_mae: 0.0684 - val_potential_mse: 0.0079 - learning_rate: 8.2597e-04
Epoch 38/1000

Epoch 38: val_loss did not improve from 0.00934
231/231 - 1s - 3ms/step - delta_h_loss: 0.0022 - delta_h_mae: 0.0360 - delta_h_mse: 0.0022 - loss: 0.0130 - potential_loss: 0.0037 - potential_mae: 0.0464 - potential_mse: 0.0037 - val_delta_h_loss: 5.5688e-04 - val_delta_h_mae: 0.0183 - val_delta_h_mse: 5.5593e-04 - val_loss: 0.0123 - val_potential_loss: 0.0035 - val_potential_mae: 0.0447 - val_potential_mse: 0.0035 - learning_rate: 8.2597e-04
Epoch 39/1000

Epoch 39: ReduceLROnPlateau reducing learning rate to 0.00041298626456409693.

Epoch 39: val_loss did not improve from 0.00934
231/231 - 1s - 2ms/step - delta_h_loss: 0.0018 - delta_h_mae: 0.0321 - delta_h_mse: 0.0018 - loss: 0.0118 - potential_loss: 0.0031 - potential_mae: 0.0439 - potential_mse: 0.0031 - val_delta_h_loss: 7.7639e-04 - val_delta_h_mae: 0.0185 - val_delta_h_mse: 7.7642e-04 - val_loss: 0.0108 - val_potential_loss: 0.0012 - val_potential_mae: 0.0264 - val_potential_mse: 0.0012 - learning_rate: 8.2597e-04
Epoch 40/1000

Epoch 40: val_loss improved from 0.00934 to 0.00709, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0259 - delta_h_mse: 0.0012 - loss: 0.0081 - potential_loss: 0.0022 - potential_mae: 0.0362 - potential_mse: 0.0022 - val_delta_h_loss: 9.3520e-04 - val_delta_h_mae: 0.0248 - val_delta_h_mse: 9.3315e-04 - val_loss: 0.0071 - val_potential_loss: 0.0017 - val_potential_mae: 0.0352 - val_potential_mse: 0.0017 - learning_rate: 4.1299e-04
Epoch 41/1000

Epoch 41: val_loss improved from 0.00709 to 0.00612, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 2ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0268 - delta_h_mse: 0.0013 - loss: 0.0079 - potential_loss: 0.0024 - potential_mae: 0.0372 - potential_mse: 0.0024 - val_delta_h_loss: 6.1884e-04 - val_delta_h_mae: 0.0189 - val_delta_h_mse: 6.2159e-04 - val_loss: 0.0061 - val_potential_loss: 6.4518e-04 - val_potential_mae: 0.0198 - val_potential_mse: 6.4530e-04 - learning_rate: 4.1299e-04
Epoch 42/1000

Epoch 42: val_loss did not improve from 0.00612
231/231 - 1s - 3ms/step - delta_h_loss: 0.0012 - delta_h_mae: 0.0266 - delta_h_mse: 0.0012 - loss: 0.0075 - potential_loss: 0.0019 - potential_mae: 0.0341 - potential_mse: 0.0019 - val_delta_h_loss: 7.3252e-04 - val_delta_h_mae: 0.0207 - val_delta_h_mse: 7.3547e-04 - val_loss: 0.0078 - val_potential_loss: 0.0037 - val_potential_mae: 0.0494 - val_potential_mse: 0.0038 - learning_rate: 4.1299e-04
Epoch 43/1000

Epoch 43: val_loss did not improve from 0.00612
231/231 - 1s - 2ms/step - delta_h_loss: 0.0013 - delta_h_mae: 0.0285 - delta_h_mse: 0.0013 - loss: 0.0075 - potential_loss: 0.0021 - potential_mae: 0.0352 - potential_mse: 0.0021 - val_delta_h_loss: 4.8637e-04 - val_delta_h_mae: 0.0170 - val_delta_h_mse: 4.8809e-04 - val_loss: 0.0081 - val_potential_loss: 0.0035 - val_potential_mae: 0.0496 - val_potential_mse: 0.0035 - learning_rate: 4.1299e-04
Epoch 44/1000

Epoch 44: val_loss did not improve from 0.00612
231/231 - 1s - 3ms/step - delta_h_loss: 0.0021 - delta_h_mae: 0.0352 - delta_h_mse: 0.0021 - loss: 0.0083 - potential_loss: 0.0023 - potential_mae: 0.0358 - potential_mse: 0.0023 - val_delta_h_loss: 0.0013 - val_delta_h_mae: 0.0281 - val_delta_h_mse: 0.0013 - val_loss: 0.0092 - val_potential_loss: 0.0032 - val_potential_mae: 0.0465 - val_potential_mse: 0.0032 - learning_rate: 4.1299e-04
Epoch 45/1000

Epoch 45: val_loss did not improve from 0.00612
231/231 - 1s - 2ms/step - delta_h_loss: 0.0014 - delta_h_mae: 0.0291 - delta_h_mse: 0.0014 - loss: 0.0081 - potential_loss: 0.0022 - potential_mae: 0.0368 - potential_mse: 0.0022 - val_delta_h_loss: 0.0016 - val_delta_h_mae: 0.0292 - val_delta_h_mse: 0.0016 - val_loss: 0.0069 - val_potential_loss: 4.3961e-04 - val_potential_mae: 0.0159 - val_potential_mse: 4.4103e-04 - learning_rate: 4.1299e-04
Epoch 46/1000

Epoch 46: val_loss did not improve from 0.00612
231/231 - 1s - 3ms/step - delta_h_loss: 0.0011 - delta_h_mae: 0.0247 - delta_h_mse: 0.0011 - loss: 0.0075 - potential_loss: 0.0019 - potential_mae: 0.0333 - potential_mse: 0.0019 - val_delta_h_loss: 9.8657e-04 - val_delta_h_mae: 0.0255 - val_delta_h_mse: 9.8495e-04 - val_loss: 0.0073 - val_potential_loss: 7.1787e-04 - val_potential_mae: 0.0217 - val_potential_mse: 7.2034e-04 - learning_rate: 4.1299e-04
Epoch 47/1000

Epoch 47: val_loss did not improve from 0.00612
231/231 - 1s - 2ms/step - delta_h_loss: 9.4682e-04 - delta_h_mae: 0.0233 - delta_h_mse: 9.4851e-04 - loss: 0.0070 - potential_loss: 0.0018 - potential_mae: 0.0329 - potential_mse: 0.0018 - val_delta_h_loss: 7.7233e-04 - val_delta_h_mae: 0.0236 - val_delta_h_mse: 7.6999e-04 - val_loss: 0.0070 - val_potential_loss: 0.0020 - val_potential_mae: 0.0342 - val_potential_mse: 0.0020 - learning_rate: 4.1299e-04
Epoch 48/1000

Epoch 48: val_loss did not improve from 0.00612
231/231 - 1s - 2ms/step - delta_h_loss: 6.6052e-04 - delta_h_mae: 0.0197 - delta_h_mse: 6.6119e-04 - loss: 0.0068 - potential_loss: 0.0019 - potential_mae: 0.0338 - potential_mse: 0.0019 - val_delta_h_loss: 1.6689e-04 - val_delta_h_mae: 0.0099 - val_delta_h_mse: 1.6752e-04 - val_loss: 0.0063 - val_potential_loss: 6.4748e-04 - val_potential_mae: 0.0197 - val_potential_mse: 6.5006e-04 - learning_rate: 4.1299e-04
Epoch 49/1000

Epoch 49: val_loss improved from 0.00612 to 0.00602, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 7.2250e-04 - delta_h_mae: 0.0200 - delta_h_mse: 7.2337e-04 - loss: 0.0066 - potential_loss: 0.0019 - potential_mae: 0.0329 - potential_mse: 0.0019 - val_delta_h_loss: 7.6057e-04 - val_delta_h_mae: 0.0204 - val_delta_h_mse: 7.6225e-04 - val_loss: 0.0060 - val_potential_loss: 0.0014 - val_potential_mae: 0.0299 - val_potential_mse: 0.0014 - learning_rate: 4.1299e-04
Epoch 50/1000

Epoch 50: val_loss improved from 0.00602 to 0.00575, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 6.9443e-04 - delta_h_mae: 0.0199 - delta_h_mse: 6.9388e-04 - loss: 0.0064 - potential_loss: 0.0016 - potential_mae: 0.0314 - potential_mse: 0.0016 - val_delta_h_loss: 6.5180e-04 - val_delta_h_mae: 0.0203 - val_delta_h_mse: 6.5366e-04 - val_loss: 0.0057 - val_potential_loss: 5.1162e-04 - val_potential_mae: 0.0176 - val_potential_mse: 5.1305e-04 - learning_rate: 4.1299e-04
Epoch 51/1000

Epoch 51: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 9.3846e-04 - delta_h_mae: 0.0233 - delta_h_mse: 9.3883e-04 - loss: 0.0068 - potential_loss: 0.0021 - potential_mae: 0.0355 - potential_mse: 0.0021 - val_delta_h_loss: 0.0024 - val_delta_h_mae: 0.0426 - val_delta_h_mse: 0.0024 - val_loss: 0.0069 - val_potential_loss: 4.7621e-04 - val_potential_mae: 0.0171 - val_potential_mse: 4.7613e-04 - learning_rate: 4.1299e-04
Epoch 52/1000

Epoch 52: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 9.0489e-04 - delta_h_mae: 0.0219 - delta_h_mse: 9.0321e-04 - loss: 0.0065 - potential_loss: 0.0015 - potential_mae: 0.0296 - potential_mse: 0.0015 - val_delta_h_loss: 0.0016 - val_delta_h_mae: 0.0286 - val_delta_h_mse: 0.0016 - val_loss: 0.0069 - val_potential_loss: 9.0142e-04 - val_potential_mae: 0.0239 - val_potential_mse: 9.0359e-04 - learning_rate: 4.1299e-04
Epoch 53/1000

Epoch 53: val_loss did not improve from 0.00575
231/231 - 1s - 2ms/step - delta_h_loss: 6.9306e-04 - delta_h_mae: 0.0198 - delta_h_mse: 6.8706e-04 - loss: 0.0065 - potential_loss: 0.0019 - potential_mae: 0.0338 - potential_mse: 0.0019 - val_delta_h_loss: 2.9466e-04 - val_delta_h_mae: 0.0128 - val_delta_h_mse: 2.9573e-04 - val_loss: 0.0068 - val_potential_loss: 0.0015 - val_potential_mae: 0.0329 - val_potential_mse: 0.0015 - learning_rate: 4.1299e-04
Epoch 54/1000

Epoch 54: val_loss did not improve from 0.00575
231/231 - 1s - 2ms/step - delta_h_loss: 7.4177e-04 - delta_h_mae: 0.0204 - delta_h_mse: 7.4289e-04 - loss: 0.0065 - potential_loss: 0.0021 - potential_mae: 0.0357 - potential_mse: 0.0021 - val_delta_h_loss: 6.6869e-04 - val_delta_h_mae: 0.0219 - val_delta_h_mse: 6.7010e-04 - val_loss: 0.0064 - val_potential_loss: 0.0021 - val_potential_mae: 0.0345 - val_potential_mse: 0.0021 - learning_rate: 4.1299e-04
Epoch 55/1000

Epoch 55: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 8.1736e-04 - delta_h_mae: 0.0216 - delta_h_mse: 8.1781e-04 - loss: 0.0063 - potential_loss: 0.0014 - potential_mae: 0.0284 - potential_mse: 0.0014 - val_delta_h_loss: 6.5523e-04 - val_delta_h_mae: 0.0203 - val_delta_h_mse: 6.5592e-04 - val_loss: 0.0062 - val_potential_loss: 0.0029 - val_potential_mae: 0.0405 - val_potential_mse: 0.0029 - learning_rate: 4.1299e-04
Epoch 56/1000

Epoch 56: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 0.0010 - delta_h_mae: 0.0233 - delta_h_mse: 0.0010 - loss: 0.0068 - potential_loss: 0.0026 - potential_mae: 0.0391 - potential_mse: 0.0026 - val_delta_h_loss: 5.8517e-04 - val_delta_h_mae: 0.0202 - val_delta_h_mse: 5.8756e-04 - val_loss: 0.0064 - val_potential_loss: 0.0028 - val_potential_mae: 0.0469 - val_potential_mse: 0.0028 - learning_rate: 4.1299e-04
Epoch 57/1000

Epoch 57: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 7.0120e-04 - delta_h_mae: 0.0200 - delta_h_mse: 7.0241e-04 - loss: 0.0064 - potential_loss: 0.0025 - potential_mae: 0.0374 - potential_mse: 0.0025 - val_delta_h_loss: 4.1423e-04 - val_delta_h_mae: 0.0162 - val_delta_h_mse: 4.1523e-04 - val_loss: 0.0066 - val_potential_loss: 0.0031 - val_potential_mae: 0.0462 - val_potential_mse: 0.0031 - learning_rate: 4.1299e-04
Epoch 58/1000

Epoch 58: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 6.9525e-04 - delta_h_mae: 0.0195 - delta_h_mse: 6.9402e-04 - loss: 0.0064 - potential_loss: 0.0028 - potential_mae: 0.0401 - potential_mse: 0.0028 - val_delta_h_loss: 0.0021 - val_delta_h_mae: 0.0365 - val_delta_h_mse: 0.0021 - val_loss: 0.0074 - val_potential_loss: 0.0025 - val_potential_mae: 0.0404 - val_potential_mse: 0.0025 - learning_rate: 4.1299e-04
Epoch 59/1000

Epoch 59: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 9.9773e-04 - delta_h_mae: 0.0250 - delta_h_mse: 9.9460e-04 - loss: 0.0067 - potential_loss: 0.0028 - potential_mae: 0.0394 - potential_mse: 0.0028 - val_delta_h_loss: 0.0013 - val_delta_h_mae: 0.0307 - val_delta_h_mse: 0.0013 - val_loss: 0.0071 - val_potential_loss: 0.0018 - val_potential_mae: 0.0366 - val_potential_mse: 0.0018 - learning_rate: 4.1299e-04
Epoch 60/1000

Epoch 60: ReduceLROnPlateau reducing learning rate to 0.00020649313228204846.

Epoch 60: val_loss did not improve from 0.00575
231/231 - 1s - 3ms/step - delta_h_loss: 0.0011 - delta_h_mae: 0.0238 - delta_h_mse: 0.0011 - loss: 0.0065 - potential_loss: 0.0021 - potential_mae: 0.0347 - potential_mse: 0.0021 - val_delta_h_loss: 8.6351e-04 - val_delta_h_mae: 0.0237 - val_delta_h_mse: 8.6122e-04 - val_loss: 0.0071 - val_potential_loss: 0.0033 - val_potential_mae: 0.0470 - val_potential_mse: 0.0033 - learning_rate: 4.1299e-04
Epoch 61/1000

Epoch 61: val_loss improved from 0.00575 to 0.00503, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 5.3599e-04 - delta_h_mae: 0.0169 - delta_h_mse: 5.3286e-04 - loss: 0.0051 - potential_loss: 0.0017 - potential_mae: 0.0313 - potential_mse: 0.0016 - val_delta_h_loss: 2.5968e-04 - val_delta_h_mae: 0.0116 - val_delta_h_mse: 2.6093e-04 - val_loss: 0.0050 - val_potential_loss: 0.0017 - val_potential_mae: 0.0350 - val_potential_mse: 0.0017 - learning_rate: 2.0649e-04
Epoch 62/1000

Epoch 62: val_loss improved from 0.00503 to 0.00468, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 2ms/step - delta_h_loss: 3.9059e-04 - delta_h_mae: 0.0148 - delta_h_mse: 3.8961e-04 - loss: 0.0048 - potential_loss: 0.0013 - potential_mae: 0.0283 - potential_mse: 0.0013 - val_delta_h_loss: 4.1482e-04 - val_delta_h_mae: 0.0157 - val_delta_h_mse: 4.1520e-04 - val_loss: 0.0047 - val_potential_loss: 8.4761e-04 - val_potential_mae: 0.0223 - val_potential_mse: 8.4372e-04 - learning_rate: 2.0649e-04
Epoch 63/1000

Epoch 63: val_loss improved from 0.00468 to 0.00437, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 4.6256e-04 - delta_h_mae: 0.0163 - delta_h_mse: 4.6349e-04 - loss: 0.0048 - potential_loss: 0.0012 - potential_mae: 0.0273 - potential_mse: 0.0012 - val_delta_h_loss: 3.0512e-04 - val_delta_h_mae: 0.0136 - val_delta_h_mse: 3.0584e-04 - val_loss: 0.0044 - val_potential_loss: 0.0016 - val_potential_mae: 0.0338 - val_potential_mse: 0.0016 - learning_rate: 2.0649e-04
Epoch 64/1000

Epoch 64: val_loss did not improve from 0.00437
231/231 - 1s - 3ms/step - delta_h_loss: 3.5120e-04 - delta_h_mae: 0.0142 - delta_h_mse: 3.5024e-04 - loss: 0.0046 - potential_loss: 0.0012 - potential_mae: 0.0262 - potential_mse: 0.0012 - val_delta_h_loss: 1.1697e-04 - val_delta_h_mae: 0.0080 - val_delta_h_mse: 1.1720e-04 - val_loss: 0.0046 - val_potential_loss: 6.0930e-04 - val_potential_mae: 0.0192 - val_potential_mse: 6.0746e-04 - learning_rate: 2.0649e-04
Epoch 65/1000

Epoch 65: val_loss did not improve from 0.00437
231/231 - 1s - 2ms/step - delta_h_loss: 3.5924e-04 - delta_h_mae: 0.0139 - delta_h_mse: 3.5915e-04 - loss: 0.0046 - potential_loss: 0.0013 - potential_mae: 0.0274 - potential_mse: 0.0013 - val_delta_h_loss: 5.3543e-04 - val_delta_h_mae: 0.0188 - val_delta_h_mse: 5.3453e-04 - val_loss: 0.0045 - val_potential_loss: 9.3923e-04 - val_potential_mae: 0.0248 - val_potential_mse: 9.4296e-04 - learning_rate: 2.0649e-04
Epoch 66/1000

Epoch 66: val_loss did not improve from 0.00437
231/231 - 1s - 3ms/step - delta_h_loss: 4.4664e-04 - delta_h_mae: 0.0157 - delta_h_mse: 4.4714e-04 - loss: 0.0046 - potential_loss: 0.0016 - potential_mae: 0.0288 - potential_mse: 0.0016 - val_delta_h_loss: 4.0622e-04 - val_delta_h_mae: 0.0170 - val_delta_h_mse: 4.0727e-04 - val_loss: 0.0045 - val_potential_loss: 0.0011 - val_potential_mae: 0.0244 - val_potential_mse: 0.0011 - learning_rate: 2.0649e-04
Epoch 67/1000

Epoch 67: val_loss improved from 0.00437 to 0.00385, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 5.2875e-04 - delta_h_mae: 0.0170 - delta_h_mse: 5.2917e-04 - loss: 0.0046 - potential_loss: 0.0018 - potential_mae: 0.0324 - potential_mse: 0.0018 - val_delta_h_loss: 1.9700e-04 - val_delta_h_mae: 0.0112 - val_delta_h_mse: 1.9750e-04 - val_loss: 0.0039 - val_potential_loss: 0.0014 - val_potential_mae: 0.0293 - val_potential_mse: 0.0014 - learning_rate: 2.0649e-04
Epoch 68/1000

Epoch 68: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 5.6764e-04 - delta_h_mae: 0.0180 - delta_h_mse: 5.6859e-04 - loss: 0.0043 - potential_loss: 0.0015 - potential_mae: 0.0290 - potential_mse: 0.0015 - val_delta_h_loss: 3.8833e-04 - val_delta_h_mae: 0.0165 - val_delta_h_mse: 3.8632e-04 - val_loss: 0.0042 - val_potential_loss: 7.8047e-04 - val_potential_mae: 0.0212 - val_potential_mse: 7.7705e-04 - learning_rate: 2.0649e-04
Epoch 69/1000

Epoch 69: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 3.8737e-04 - delta_h_mae: 0.0149 - delta_h_mse: 3.8790e-04 - loss: 0.0042 - potential_loss: 0.0015 - potential_mae: 0.0298 - potential_mse: 0.0015 - val_delta_h_loss: 4.3696e-04 - val_delta_h_mae: 0.0154 - val_delta_h_mse: 4.3806e-04 - val_loss: 0.0045 - val_potential_loss: 0.0016 - val_potential_mae: 0.0321 - val_potential_mse: 0.0016 - learning_rate: 2.0649e-04
Epoch 70/1000

Epoch 70: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 3.8538e-04 - delta_h_mae: 0.0149 - delta_h_mse: 3.8631e-04 - loss: 0.0041 - potential_loss: 0.0014 - potential_mae: 0.0284 - potential_mse: 0.0014 - val_delta_h_loss: 9.4065e-04 - val_delta_h_mae: 0.0243 - val_delta_h_mse: 9.4402e-04 - val_loss: 0.0042 - val_potential_loss: 6.1456e-04 - val_potential_mae: 0.0193 - val_potential_mse: 6.1598e-04 - learning_rate: 2.0649e-04
Epoch 71/1000

Epoch 71: val_loss improved from 0.00385 to 0.00385, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 4.3312e-04 - delta_h_mae: 0.0158 - delta_h_mse: 4.3359e-04 - loss: 0.0042 - potential_loss: 0.0017 - potential_mae: 0.0309 - potential_mse: 0.0017 - val_delta_h_loss: 4.1601e-04 - val_delta_h_mae: 0.0155 - val_delta_h_mse: 4.1306e-04 - val_loss: 0.0038 - val_potential_loss: 0.0016 - val_potential_mae: 0.0325 - val_potential_mse: 0.0016 - learning_rate: 2.0649e-04
Epoch 72/1000

Epoch 72: val_loss did not improve from 0.00385
231/231 - 1s - 2ms/step - delta_h_loss: 6.0404e-04 - delta_h_mae: 0.0188 - delta_h_mse: 6.0539e-04 - loss: 0.0043 - potential_loss: 0.0016 - potential_mae: 0.0299 - potential_mse: 0.0016 - val_delta_h_loss: 6.6280e-04 - val_delta_h_mae: 0.0211 - val_delta_h_mse: 6.6173e-04 - val_loss: 0.0043 - val_potential_loss: 0.0011 - val_potential_mae: 0.0276 - val_potential_mse: 0.0011 - learning_rate: 2.0649e-04
Epoch 73/1000

Epoch 73: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 5.8751e-04 - delta_h_mae: 0.0182 - delta_h_mse: 5.8802e-04 - loss: 0.0044 - potential_loss: 0.0017 - potential_mae: 0.0306 - potential_mse: 0.0017 - val_delta_h_loss: 0.0011 - val_delta_h_mae: 0.0253 - val_delta_h_mse: 0.0011 - val_loss: 0.0043 - val_potential_loss: 0.0013 - val_potential_mae: 0.0308 - val_potential_mse: 0.0013 - learning_rate: 2.0649e-04
Epoch 74/1000

Epoch 74: val_loss did not improve from 0.00385
231/231 - 1s - 2ms/step - delta_h_loss: 4.6076e-04 - delta_h_mae: 0.0164 - delta_h_mse: 4.6064e-04 - loss: 0.0042 - potential_loss: 0.0016 - potential_mae: 0.0298 - potential_mse: 0.0016 - val_delta_h_loss: 2.5593e-04 - val_delta_h_mae: 0.0120 - val_delta_h_mse: 2.5637e-04 - val_loss: 0.0042 - val_potential_loss: 8.8629e-04 - val_potential_mae: 0.0240 - val_potential_mse: 8.8597e-04 - learning_rate: 2.0649e-04
Epoch 75/1000

Epoch 75: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 4.4259e-04 - delta_h_mae: 0.0158 - delta_h_mse: 4.4324e-04 - loss: 0.0042 - potential_loss: 0.0015 - potential_mae: 0.0298 - potential_mse: 0.0015 - val_delta_h_loss: 4.5810e-04 - val_delta_h_mae: 0.0169 - val_delta_h_mse: 4.5934e-04 - val_loss: 0.0040 - val_potential_loss: 0.0013 - val_potential_mae: 0.0290 - val_potential_mse: 0.0013 - learning_rate: 2.0649e-04
Epoch 76/1000

Epoch 76: val_loss did not improve from 0.00385
231/231 - 1s - 2ms/step - delta_h_loss: 3.9902e-04 - delta_h_mae: 0.0150 - delta_h_mse: 3.9927e-04 - loss: 0.0041 - potential_loss: 0.0016 - potential_mae: 0.0308 - potential_mse: 0.0016 - val_delta_h_loss: 3.6431e-04 - val_delta_h_mae: 0.0149 - val_delta_h_mse: 3.6437e-04 - val_loss: 0.0042 - val_potential_loss: 8.8142e-04 - val_potential_mae: 0.0234 - val_potential_mse: 8.8254e-04 - learning_rate: 2.0649e-04
Epoch 77/1000

Epoch 77: ReduceLROnPlateau reducing learning rate to 0.00010324656614102423.

Epoch 77: val_loss did not improve from 0.00385
231/231 - 1s - 3ms/step - delta_h_loss: 4.4582e-04 - delta_h_mae: 0.0154 - delta_h_mse: 4.4613e-04 - loss: 0.0041 - potential_loss: 0.0014 - potential_mae: 0.0286 - potential_mse: 0.0014 - val_delta_h_loss: 2.4795e-04 - val_delta_h_mae: 0.0123 - val_delta_h_mse: 2.4891e-04 - val_loss: 0.0040 - val_potential_loss: 0.0018 - val_potential_mae: 0.0344 - val_potential_mse: 0.0018 - learning_rate: 2.0649e-04
Epoch 78/1000

Epoch 78: val_loss improved from 0.00385 to 0.00264, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 2.4847e-04 - delta_h_mae: 0.0119 - delta_h_mse: 2.4851e-04 - loss: 0.0030 - potential_loss: 0.0011 - potential_mae: 0.0252 - potential_mse: 0.0011 - val_delta_h_loss: 1.1510e-04 - val_delta_h_mae: 0.0080 - val_delta_h_mse: 1.1429e-04 - val_loss: 0.0026 - val_potential_loss: 6.8250e-04 - val_potential_mae: 0.0191 - val_potential_mse: 6.6953e-04 - learning_rate: 1.0325e-04
Epoch 79/1000

Epoch 79: val_loss did not improve from 0.00264
231/231 - 1s - 3ms/step - delta_h_loss: 1.9498e-04 - delta_h_mae: 0.0106 - delta_h_mse: 1.9377e-04 - loss: 0.0029 - potential_loss: 0.0011 - potential_mae: 0.0255 - potential_mse: 0.0011 - val_delta_h_loss: 6.2234e-04 - val_delta_h_mae: 0.0204 - val_delta_h_mse: 6.1817e-04 - val_loss: 0.0031 - val_potential_loss: 0.0011 - val_potential_mae: 0.0268 - val_potential_mse: 0.0011 - learning_rate: 1.0325e-04
Epoch 80/1000

Epoch 80: val_loss did not improve from 0.00264
231/231 - 1s - 2ms/step - delta_h_loss: 2.9455e-04 - delta_h_mae: 0.0133 - delta_h_mse: 2.9519e-04 - loss: 0.0030 - potential_loss: 0.0013 - potential_mae: 0.0265 - potential_mse: 0.0013 - val_delta_h_loss: 1.3143e-04 - val_delta_h_mae: 0.0086 - val_delta_h_mse: 1.3178e-04 - val_loss: 0.0031 - val_potential_loss: 0.0018 - val_potential_mae: 0.0358 - val_potential_mse: 0.0018 - learning_rate: 1.0325e-04
Epoch 81/1000

Epoch 81: val_loss did not improve from 0.00264
231/231 - 1s - 3ms/step - delta_h_loss: 2.5804e-04 - delta_h_mae: 0.0122 - delta_h_mse: 2.5866e-04 - loss: 0.0030 - potential_loss: 0.0012 - potential_mae: 0.0266 - potential_mse: 0.0012 - val_delta_h_loss: 2.4415e-04 - val_delta_h_mae: 0.0118 - val_delta_h_mse: 2.4336e-04 - val_loss: 0.0027 - val_potential_loss: 3.3959e-04 - val_potential_mae: 0.0143 - val_potential_mse: 3.3794e-04 - learning_rate: 1.0325e-04
Epoch 82/1000

Epoch 82: val_loss did not improve from 0.00264
231/231 - 1s - 3ms/step - delta_h_loss: 2.8475e-04 - delta_h_mae: 0.0123 - delta_h_mse: 2.7262e-04 - loss: 0.0030 - potential_loss: 0.0012 - potential_mae: 0.0249 - potential_mse: 0.0012 - val_delta_h_loss: 2.2549e-04 - val_delta_h_mae: 0.0119 - val_delta_h_mse: 2.2600e-04 - val_loss: 0.0031 - val_potential_loss: 0.0015 - val_potential_mae: 0.0293 - val_potential_mse: 0.0015 - learning_rate: 1.0325e-04
Epoch 83/1000

Epoch 83: val_loss improved from 0.00264 to 0.00257, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 3.2342e-04 - delta_h_mae: 0.0138 - delta_h_mse: 3.2398e-04 - loss: 0.0030 - potential_loss: 0.0013 - potential_mae: 0.0267 - potential_mse: 0.0013 - val_delta_h_loss: 1.0981e-04 - val_delta_h_mae: 0.0080 - val_delta_h_mse: 1.0944e-04 - val_loss: 0.0026 - val_potential_loss: 4.0194e-04 - val_potential_mae: 0.0137 - val_potential_mse: 3.9384e-04 - learning_rate: 1.0325e-04
Epoch 84/1000

Epoch 84: val_loss did not improve from 0.00257
231/231 - 1s - 3ms/step - delta_h_loss: 2.4897e-04 - delta_h_mae: 0.0119 - delta_h_mse: 2.4911e-04 - loss: 0.0029 - potential_loss: 0.0013 - potential_mae: 0.0265 - potential_mse: 0.0013 - val_delta_h_loss: 1.9257e-04 - val_delta_h_mae: 0.0104 - val_delta_h_mse: 1.9167e-04 - val_loss: 0.0029 - val_potential_loss: 0.0013 - val_potential_mae: 0.0295 - val_potential_mse: 0.0013 - learning_rate: 1.0325e-04
Epoch 85/1000

Epoch 85: val_loss did not improve from 0.00257
231/231 - 1s - 3ms/step - delta_h_loss: 2.3078e-04 - delta_h_mae: 0.0114 - delta_h_mse: 2.3091e-04 - loss: 0.0029 - potential_loss: 0.0012 - potential_mae: 0.0265 - potential_mse: 0.0012 - val_delta_h_loss: 1.9769e-04 - val_delta_h_mae: 0.0110 - val_delta_h_mse: 1.9834e-04 - val_loss: 0.0026 - val_potential_loss: 5.6228e-04 - val_potential_mae: 0.0182 - val_potential_mse: 5.6299e-04 - learning_rate: 1.0325e-04
Epoch 86/1000

Epoch 86: val_loss did not improve from 0.00257
231/231 - 1s - 3ms/step - delta_h_loss: 3.1150e-04 - delta_h_mae: 0.0132 - delta_h_mse: 3.1168e-04 - loss: 0.0031 - potential_loss: 0.0017 - potential_mae: 0.0282 - potential_mse: 0.0017 - val_delta_h_loss: 4.4003e-04 - val_delta_h_mae: 0.0179 - val_delta_h_mse: 4.3927e-04 - val_loss: 0.0029 - val_potential_loss: 0.0011 - val_potential_mae: 0.0274 - val_potential_mse: 0.0011 - learning_rate: 1.0325e-04
Epoch 87/1000

Epoch 87: val_loss did not improve from 0.00257
231/231 - 1s - 2ms/step - delta_h_loss: 2.3064e-04 - delta_h_mae: 0.0116 - delta_h_mse: 2.2996e-04 - loss: 0.0030 - potential_loss: 0.0017 - potential_mae: 0.0304 - potential_mse: 0.0017 - val_delta_h_loss: 2.0550e-04 - val_delta_h_mae: 0.0115 - val_delta_h_mse: 2.0593e-04 - val_loss: 0.0028 - val_potential_loss: 6.9573e-04 - val_potential_mae: 0.0191 - val_potential_mse: 6.9963e-04 - learning_rate: 1.0325e-04
Epoch 88/1000

Epoch 88: ReduceLROnPlateau reducing learning rate to 5.1623283070512116e-05.

Epoch 88: val_loss did not improve from 0.00257
231/231 - 1s - 3ms/step - delta_h_loss: 2.4766e-04 - delta_h_mae: 0.0118 - delta_h_mse: 2.4770e-04 - loss: 0.0029 - potential_loss: 0.0013 - potential_mae: 0.0265 - potential_mse: 0.0013 - val_delta_h_loss: 1.8538e-04 - val_delta_h_mae: 0.0108 - val_delta_h_mse: 1.8446e-04 - val_loss: 0.0034 - val_potential_loss: 0.0030 - val_potential_mae: 0.0397 - val_potential_mse: 0.0030 - learning_rate: 1.0325e-04
Epoch 89/1000

Epoch 89: val_loss improved from 0.00257 to 0.00229, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.9824e-04 - delta_h_mae: 0.0103 - delta_h_mse: 1.9862e-04 - loss: 0.0026 - potential_loss: 0.0015 - potential_mae: 0.0278 - potential_mse: 0.0015 - val_delta_h_loss: 1.3038e-04 - val_delta_h_mae: 0.0085 - val_delta_h_mse: 1.3085e-04 - val_loss: 0.0023 - val_potential_loss: 6.1532e-04 - val_potential_mae: 0.0191 - val_potential_mse: 6.0781e-04 - learning_rate: 5.1623e-05
Epoch 90/1000

Epoch 90: val_loss improved from 0.00229 to 0.00225, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.6177e-04 - delta_h_mae: 0.0094 - delta_h_mse: 1.6202e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0238 - potential_mse: 0.0011 - val_delta_h_loss: 1.4262e-04 - val_delta_h_mae: 0.0087 - val_delta_h_mse: 1.4309e-04 - val_loss: 0.0022 - val_potential_loss: 7.3175e-04 - val_potential_mae: 0.0217 - val_potential_mse: 7.3403e-04 - learning_rate: 5.1623e-05
Epoch 91/1000

Epoch 91: val_loss improved from 0.00225 to 0.00224, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.6324e-04 - delta_h_mae: 0.0094 - delta_h_mse: 1.6299e-04 - loss: 0.0025 - potential_loss: 0.0012 - potential_mae: 0.0248 - potential_mse: 0.0012 - val_delta_h_loss: 1.6131e-04 - val_delta_h_mae: 0.0100 - val_delta_h_mse: 1.6192e-04 - val_loss: 0.0022 - val_potential_loss: 5.8333e-04 - val_potential_mae: 0.0180 - val_potential_mse: 5.7321e-04 - learning_rate: 5.1623e-05
Epoch 92/1000

Epoch 92: val_loss did not improve from 0.00224
231/231 - 1s - 3ms/step - delta_h_loss: 1.7363e-04 - delta_h_mae: 0.0098 - delta_h_mse: 1.7402e-04 - loss: 0.0024 - potential_loss: 0.0010 - potential_mae: 0.0232 - potential_mse: 0.0010 - val_delta_h_loss: 2.2379e-04 - val_delta_h_mae: 0.0119 - val_delta_h_mse: 2.2440e-04 - val_loss: 0.0024 - val_potential_loss: 6.6705e-04 - val_potential_mae: 0.0201 - val_potential_mse: 6.6380e-04 - learning_rate: 5.1623e-05
Epoch 93/1000

Epoch 93: val_loss did not improve from 0.00224
231/231 - 1s - 2ms/step - delta_h_loss: 1.9359e-04 - delta_h_mae: 0.0105 - delta_h_mse: 1.9373e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0232 - potential_mse: 0.0011 - val_delta_h_loss: 1.3751e-04 - val_delta_h_mae: 0.0093 - val_delta_h_mse: 1.3790e-04 - val_loss: 0.0023 - val_potential_loss: 4.5304e-04 - val_potential_mae: 0.0159 - val_potential_mse: 4.5165e-04 - learning_rate: 5.1623e-05
Epoch 94/1000

Epoch 94: val_loss improved from 0.00224 to 0.00223, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.8371e-04 - delta_h_mae: 0.0100 - delta_h_mse: 1.8344e-04 - loss: 0.0025 - potential_loss: 0.0012 - potential_mae: 0.0247 - potential_mse: 0.0012 - val_delta_h_loss: 1.1362e-04 - val_delta_h_mae: 0.0079 - val_delta_h_mse: 1.1325e-04 - val_loss: 0.0022 - val_potential_loss: 6.9344e-04 - val_potential_mae: 0.0217 - val_potential_mse: 6.8990e-04 - learning_rate: 5.1623e-05
Epoch 95/1000

Epoch 95: val_loss did not improve from 0.00223
231/231 - 1s - 3ms/step - delta_h_loss: 1.9128e-04 - delta_h_mae: 0.0100 - delta_h_mse: 1.9039e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0242 - potential_mse: 0.0011 - val_delta_h_loss: 4.6107e-04 - val_delta_h_mae: 0.0168 - val_delta_h_mse: 4.6244e-04 - val_loss: 0.0023 - val_potential_loss: 3.9177e-04 - val_potential_mae: 0.0140 - val_potential_mse: 3.8429e-04 - learning_rate: 5.1623e-05
Epoch 96/1000

Epoch 96: val_loss improved from 0.00223 to 0.00214, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.9784e-04 - delta_h_mae: 0.0106 - delta_h_mse: 1.9766e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0242 - potential_mse: 0.0011 - val_delta_h_loss: 1.7769e-04 - val_delta_h_mae: 0.0099 - val_delta_h_mse: 1.7840e-04 - val_loss: 0.0021 - val_potential_loss: 4.1631e-04 - val_potential_mae: 0.0155 - val_potential_mse: 4.1130e-04 - learning_rate: 5.1623e-05
Epoch 97/1000

Epoch 97: val_loss did not improve from 0.00214
231/231 - 1s - 3ms/step - delta_h_loss: 1.9183e-04 - delta_h_mae: 0.0104 - delta_h_mse: 1.9198e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0245 - potential_mse: 0.0011 - val_delta_h_loss: 1.9447e-04 - val_delta_h_mae: 0.0106 - val_delta_h_mse: 1.9449e-04 - val_loss: 0.0023 - val_potential_loss: 5.4981e-04 - val_potential_mae: 0.0181 - val_potential_mse: 5.4167e-04 - learning_rate: 5.1623e-05
Epoch 98/1000

Epoch 98: val_loss did not improve from 0.00214
231/231 - 1s - 3ms/step - delta_h_loss: 1.9146e-04 - delta_h_mae: 0.0103 - delta_h_mse: 1.8993e-04 - loss: 0.0024 - potential_loss: 0.0010 - potential_mae: 0.0235 - potential_mse: 0.0010 - val_delta_h_loss: 9.8379e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8265e-05 - val_loss: 0.0022 - val_potential_loss: 4.4164e-04 - val_potential_mae: 0.0154 - val_potential_mse: 4.3976e-04 - learning_rate: 5.1623e-05
Epoch 99/1000

Epoch 99: val_loss did not improve from 0.00214
231/231 - 1s - 3ms/step - delta_h_loss: 2.2008e-04 - delta_h_mae: 0.0110 - delta_h_mse: 2.2044e-04 - loss: 0.0024 - potential_loss: 0.0010 - potential_mae: 0.0243 - potential_mse: 0.0010 - val_delta_h_loss: 2.2327e-04 - val_delta_h_mae: 0.0122 - val_delta_h_mse: 2.2397e-04 - val_loss: 0.0022 - val_potential_loss: 3.6891e-04 - val_potential_mae: 0.0134 - val_potential_mse: 3.6391e-04 - learning_rate: 5.1623e-05
Epoch 100/1000

Epoch 100: val_loss improved from 0.00214 to 0.00208, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 2.2516e-04 - delta_h_mae: 0.0112 - delta_h_mse: 2.2548e-04 - loss: 0.0024 - potential_loss: 0.0011 - potential_mae: 0.0234 - potential_mse: 0.0011 - val_delta_h_loss: 1.2729e-04 - val_delta_h_mae: 0.0087 - val_delta_h_mse: 1.2672e-04 - val_loss: 0.0021 - val_potential_loss: 6.0293e-04 - val_potential_mae: 0.0184 - val_potential_mse: 6.0345e-04 - learning_rate: 5.1623e-05
Epoch 101/1000

Epoch 101: val_loss did not improve from 0.00208
231/231 - 1s - 3ms/step - delta_h_loss: 2.6137e-04 - delta_h_mae: 0.0118 - delta_h_mse: 2.6123e-04 - loss: 0.0025 - potential_loss: 0.0014 - potential_mae: 0.0265 - potential_mse: 0.0014 - val_delta_h_loss: 4.2466e-04 - val_delta_h_mae: 0.0177 - val_delta_h_mse: 4.2598e-04 - val_loss: 0.0023 - val_potential_loss: 6.6668e-04 - val_potential_mae: 0.0204 - val_potential_mse: 6.6032e-04 - learning_rate: 5.1623e-05
Epoch 102/1000

Epoch 102: val_loss did not improve from 0.00208
231/231 - 1s - 3ms/step - delta_h_loss: 2.3773e-04 - delta_h_mae: 0.0115 - delta_h_mse: 2.3786e-04 - loss: 0.0025 - potential_loss: 0.0014 - potential_mae: 0.0263 - potential_mse: 0.0014 - val_delta_h_loss: 1.3018e-04 - val_delta_h_mae: 0.0085 - val_delta_h_mse: 1.3038e-04 - val_loss: 0.0021 - val_potential_loss: 3.9442e-04 - val_potential_mae: 0.0141 - val_potential_mse: 3.8635e-04 - learning_rate: 5.1623e-05
Epoch 103/1000

Epoch 103: val_loss did not improve from 0.00208
231/231 - 1s - 3ms/step - delta_h_loss: 2.1021e-04 - delta_h_mae: 0.0106 - delta_h_mse: 2.0898e-04 - loss: 0.0025 - potential_loss: 0.0014 - potential_mae: 0.0263 - potential_mse: 0.0014 - val_delta_h_loss: 2.7055e-04 - val_delta_h_mae: 0.0130 - val_delta_h_mse: 2.7158e-04 - val_loss: 0.0022 - val_potential_loss: 3.8976e-04 - val_potential_mae: 0.0132 - val_potential_mse: 3.8126e-04 - learning_rate: 5.1623e-05
Epoch 104/1000

Epoch 104: val_loss did not improve from 0.00208
231/231 - 1s - 2ms/step - delta_h_loss: 1.8597e-04 - delta_h_mae: 0.0103 - delta_h_mse: 1.8573e-04 - loss: 0.0025 - potential_loss: 0.0015 - potential_mae: 0.0280 - potential_mse: 0.0015 - val_delta_h_loss: 1.1384e-04 - val_delta_h_mae: 0.0085 - val_delta_h_mse: 1.1400e-04 - val_loss: 0.0023 - val_potential_loss: 0.0010 - val_potential_mae: 0.0235 - val_potential_mse: 0.0010 - learning_rate: 5.1623e-05
Epoch 105/1000

Epoch 105: val_loss did not improve from 0.00208
231/231 - 1s - 3ms/step - delta_h_loss: 2.1054e-04 - delta_h_mae: 0.0108 - delta_h_mse: 2.1008e-04 - loss: 0.0025 - potential_loss: 0.0014 - potential_mae: 0.0275 - potential_mse: 0.0014 - val_delta_h_loss: 2.5965e-04 - val_delta_h_mae: 0.0133 - val_delta_h_mse: 2.6063e-04 - val_loss: 0.0021 - val_potential_loss: 5.9981e-04 - val_potential_mae: 0.0190 - val_potential_mse: 5.9617e-04 - learning_rate: 5.1623e-05
Epoch 106/1000

Epoch 106: ReduceLROnPlateau reducing learning rate to 2.5811641535256058e-05.

Epoch 106: val_loss did not improve from 0.00208
231/231 - 1s - 3ms/step - delta_h_loss: 2.1684e-04 - delta_h_mae: 0.0110 - delta_h_mse: 2.1634e-04 - loss: 0.0026 - potential_loss: 0.0019 - potential_mae: 0.0295 - potential_mse: 0.0019 - val_delta_h_loss: 1.2191e-04 - val_delta_h_mae: 0.0087 - val_delta_h_mse: 1.2226e-04 - val_loss: 0.0021 - val_potential_loss: 6.0461e-04 - val_potential_mae: 0.0183 - val_potential_mse: 5.9376e-04 - learning_rate: 5.1623e-05
Epoch 107/1000

Epoch 107: val_loss improved from 0.00208 to 0.00178, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.6892e-04 - delta_h_mae: 0.0094 - delta_h_mse: 1.6704e-04 - loss: 0.0023 - potential_loss: 0.0018 - potential_mae: 0.0267 - potential_mse: 0.0018 - val_delta_h_loss: 1.1552e-04 - val_delta_h_mae: 0.0081 - val_delta_h_mse: 1.1531e-04 - val_loss: 0.0018 - val_potential_loss: 4.6536e-04 - val_potential_mae: 0.0160 - val_potential_mse: 4.6370e-04 - learning_rate: 2.5812e-05
Epoch 108/1000

Epoch 108: val_loss did not improve from 0.00178
231/231 - 1s - 2ms/step - delta_h_loss: 1.6813e-04 - delta_h_mae: 0.0096 - delta_h_mse: 1.6821e-04 - loss: 0.0021 - potential_loss: 0.0013 - potential_mae: 0.0261 - potential_mse: 0.0013 - val_delta_h_loss: 1.1130e-04 - val_delta_h_mae: 0.0081 - val_delta_h_mse: 1.1143e-04 - val_loss: 0.0019 - val_potential_loss: 7.8842e-04 - val_potential_mae: 0.0209 - val_potential_mse: 7.8993e-04 - learning_rate: 2.5812e-05
Epoch 109/1000

Epoch 109: val_loss did not improve from 0.00178
231/231 - 1s - 2ms/step - delta_h_loss: 1.5744e-04 - delta_h_mae: 0.0094 - delta_h_mse: 1.5713e-04 - loss: 0.0022 - potential_loss: 0.0014 - potential_mae: 0.0264 - potential_mse: 0.0014 - val_delta_h_loss: 1.5384e-04 - val_delta_h_mae: 0.0093 - val_delta_h_mse: 1.5365e-04 - val_loss: 0.0020 - val_potential_loss: 9.9093e-04 - val_potential_mae: 0.0252 - val_potential_mse: 9.9056e-04 - learning_rate: 2.5812e-05
Epoch 110/1000

Epoch 110: val_loss did not improve from 0.00178
231/231 - 1s - 3ms/step - delta_h_loss: 1.8341e-04 - delta_h_mae: 0.0098 - delta_h_mse: 1.8361e-04 - loss: 0.0023 - potential_loss: 0.0019 - potential_mae: 0.0275 - potential_mse: 0.0019 - val_delta_h_loss: 1.4900e-04 - val_delta_h_mae: 0.0091 - val_delta_h_mse: 1.4895e-04 - val_loss: 0.0020 - val_potential_loss: 9.6403e-04 - val_potential_mae: 0.0248 - val_potential_mse: 9.5658e-04 - learning_rate: 2.5812e-05
Epoch 111/1000

Epoch 111: val_loss improved from 0.00178 to 0.00173, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.8353e-04 - delta_h_mae: 0.0099 - delta_h_mse: 1.8366e-04 - loss: 0.0022 - potential_loss: 0.0015 - potential_mae: 0.0270 - potential_mse: 0.0015 - val_delta_h_loss: 1.3344e-04 - val_delta_h_mae: 0.0089 - val_delta_h_mse: 1.3352e-04 - val_loss: 0.0017 - val_potential_loss: 3.7046e-04 - val_potential_mae: 0.0137 - val_potential_mse: 3.6317e-04 - learning_rate: 2.5812e-05
Epoch 112/1000

Epoch 112: val_loss did not improve from 0.00173
231/231 - 1s - 3ms/step - delta_h_loss: 1.6818e-04 - delta_h_mae: 0.0095 - delta_h_mse: 1.6842e-04 - loss: 0.0022 - potential_loss: 0.0016 - potential_mae: 0.0269 - potential_mse: 0.0016 - val_delta_h_loss: 1.1308e-04 - val_delta_h_mae: 0.0078 - val_delta_h_mse: 1.1340e-04 - val_loss: 0.0018 - val_potential_loss: 4.0974e-04 - val_potential_mae: 0.0149 - val_potential_mse: 4.0210e-04 - learning_rate: 2.5812e-05
Epoch 113/1000

Epoch 113: val_loss did not improve from 0.00173
231/231 - 1s - 2ms/step - delta_h_loss: 1.7301e-04 - delta_h_mae: 0.0097 - delta_h_mse: 1.7277e-04 - loss: 0.0023 - potential_loss: 0.0020 - potential_mae: 0.0296 - potential_mse: 0.0020 - val_delta_h_loss: 1.8697e-04 - val_delta_h_mae: 0.0110 - val_delta_h_mse: 1.8680e-04 - val_loss: 0.0020 - val_potential_loss: 8.7672e-04 - val_potential_mae: 0.0246 - val_potential_mse: 8.7360e-04 - learning_rate: 2.5812e-05
Epoch 114/1000

Epoch 114: val_loss did not improve from 0.00173
231/231 - 1s - 3ms/step - delta_h_loss: 1.9534e-04 - delta_h_mae: 0.0100 - delta_h_mse: 1.9536e-04 - loss: 0.0023 - potential_loss: 0.0018 - potential_mae: 0.0274 - potential_mse: 0.0018 - val_delta_h_loss: 2.0333e-04 - val_delta_h_mae: 0.0111 - val_delta_h_mse: 2.0212e-04 - val_loss: 0.0020 - val_potential_loss: 9.2337e-04 - val_potential_mae: 0.0252 - val_potential_mse: 9.1697e-04 - learning_rate: 2.5812e-05
Epoch 115/1000

Epoch 115: val_loss did not improve from 0.00173
231/231 - 1s - 3ms/step - delta_h_loss: 1.7919e-04 - delta_h_mae: 0.0099 - delta_h_mse: 1.7957e-04 - loss: 0.0024 - potential_loss: 0.0021 - potential_mae: 0.0310 - potential_mse: 0.0021 - val_delta_h_loss: 1.7825e-04 - val_delta_h_mae: 0.0110 - val_delta_h_mse: 1.7889e-04 - val_loss: 0.0021 - val_potential_loss: 0.0013 - val_potential_mae: 0.0272 - val_potential_mse: 0.0013 - learning_rate: 2.5812e-05
Epoch 116/1000

Epoch 116: val_loss did not improve from 0.00173
231/231 - 1s - 3ms/step - delta_h_loss: 1.9347e-04 - delta_h_mae: 0.0100 - delta_h_mse: 1.9332e-04 - loss: 0.0022 - potential_loss: 0.0017 - potential_mae: 0.0277 - potential_mse: 0.0017 - val_delta_h_loss: 1.6672e-04 - val_delta_h_mae: 0.0104 - val_delta_h_mse: 1.6735e-04 - val_loss: 0.0017 - val_potential_loss: 4.2601e-04 - val_potential_mae: 0.0151 - val_potential_mse: 4.2203e-04 - learning_rate: 2.5812e-05
Epoch 117/1000

Epoch 117: ReduceLROnPlateau reducing learning rate to 1.2905820767628029e-05.

Epoch 117: val_loss did not improve from 0.00173
231/231 - 1s - 3ms/step - delta_h_loss: 1.6352e-04 - delta_h_mae: 0.0095 - delta_h_mse: 1.6262e-04 - loss: 0.0022 - potential_loss: 0.0017 - potential_mae: 0.0285 - potential_mse: 0.0017 - val_delta_h_loss: 1.7618e-04 - val_delta_h_mae: 0.0109 - val_delta_h_mse: 1.7680e-04 - val_loss: 0.0019 - val_potential_loss: 7.9350e-04 - val_potential_mae: 0.0225 - val_potential_mse: 7.8791e-04 - learning_rate: 2.5812e-05
Epoch 118/1000

Epoch 118: val_loss improved from 0.00173 to 0.00168, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.5248e-04 - delta_h_mae: 0.0088 - delta_h_mse: 1.5241e-04 - loss: 0.0021 - potential_loss: 0.0017 - potential_mae: 0.0275 - potential_mse: 0.0017 - val_delta_h_loss: 1.3716e-04 - val_delta_h_mae: 0.0088 - val_delta_h_mse: 1.3647e-04 - val_loss: 0.0017 - val_potential_loss: 5.5416e-04 - val_potential_mae: 0.0181 - val_potential_mse: 5.4862e-04 - learning_rate: 1.2906e-05
Epoch 119/1000

Epoch 119: val_loss improved from 0.00168 to 0.00161, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.5567e-04 - delta_h_mae: 0.0090 - delta_h_mse: 1.5567e-04 - loss: 0.0021 - potential_loss: 0.0018 - potential_mae: 0.0270 - potential_mse: 0.0018 - val_delta_h_loss: 9.9335e-05 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 9.9345e-05 - val_loss: 0.0016 - val_potential_loss: 3.9954e-04 - val_potential_mae: 0.0147 - val_potential_mse: 3.9320e-04 - learning_rate: 1.2906e-05
Epoch 120/1000

Epoch 120: val_loss did not improve from 0.00161
231/231 - 1s - 2ms/step - delta_h_loss: 1.4332e-04 - delta_h_mae: 0.0089 - delta_h_mse: 1.4357e-04 - loss: 0.0020 - potential_loss: 0.0014 - potential_mae: 0.0259 - potential_mse: 0.0014 - val_delta_h_loss: 1.0551e-04 - val_delta_h_mae: 0.0079 - val_delta_h_mse: 1.0527e-04 - val_loss: 0.0016 - val_potential_loss: 4.3716e-04 - val_potential_mae: 0.0158 - val_potential_mse: 4.3277e-04 - learning_rate: 1.2906e-05
Epoch 121/1000

Epoch 121: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.3666e-04 - delta_h_mae: 0.0086 - delta_h_mse: 1.3672e-04 - loss: 0.0022 - potential_loss: 0.0021 - potential_mae: 0.0301 - potential_mse: 0.0021 - val_delta_h_loss: 1.6831e-04 - val_delta_h_mae: 0.0101 - val_delta_h_mse: 1.6893e-04 - val_loss: 0.0017 - val_potential_loss: 5.1502e-04 - val_potential_mae: 0.0161 - val_potential_mse: 5.0401e-04 - learning_rate: 1.2906e-05
Epoch 122/1000

Epoch 122: val_loss did not improve from 0.00161
231/231 - 1s - 2ms/step - delta_h_loss: 1.7360e-04 - delta_h_mae: 0.0089 - delta_h_mse: 1.7365e-04 - loss: 0.0020 - potential_loss: 0.0015 - potential_mae: 0.0265 - potential_mse: 0.0015 - val_delta_h_loss: 1.4019e-04 - val_delta_h_mae: 0.0088 - val_delta_h_mse: 1.4020e-04 - val_loss: 0.0017 - val_potential_loss: 5.3609e-04 - val_potential_mae: 0.0177 - val_potential_mse: 5.2852e-04 - learning_rate: 1.2906e-05
Epoch 123/1000

Epoch 123: val_loss did not improve from 0.00161
231/231 - 1s - 2ms/step - delta_h_loss: 1.6092e-04 - delta_h_mae: 0.0091 - delta_h_mse: 1.5971e-04 - loss: 0.0020 - potential_loss: 0.0016 - potential_mae: 0.0277 - potential_mse: 0.0016 - val_delta_h_loss: 1.6374e-04 - val_delta_h_mae: 0.0098 - val_delta_h_mse: 1.6296e-04 - val_loss: 0.0017 - val_potential_loss: 5.5076e-04 - val_potential_mae: 0.0165 - val_potential_mse: 5.3841e-04 - learning_rate: 1.2906e-05
Epoch 124/1000

Epoch 124: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.3827e-04 - delta_h_mae: 0.0087 - delta_h_mse: 1.3734e-04 - loss: 0.0021 - potential_loss: 0.0018 - potential_mae: 0.0275 - potential_mse: 0.0017 - val_delta_h_loss: 1.3363e-04 - val_delta_h_mae: 0.0089 - val_delta_h_mse: 1.3338e-04 - val_loss: 0.0016 - val_potential_loss: 3.6755e-04 - val_potential_mae: 0.0138 - val_potential_mse: 3.6234e-04 - learning_rate: 1.2906e-05
Epoch 125/1000

Epoch 125: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.4424e-04 - delta_h_mae: 0.0089 - delta_h_mse: 1.4426e-04 - loss: 0.0021 - potential_loss: 0.0017 - potential_mae: 0.0273 - potential_mse: 0.0017 - val_delta_h_loss: 1.2613e-04 - val_delta_h_mae: 0.0086 - val_delta_h_mse: 1.2639e-04 - val_loss: 0.0016 - val_potential_loss: 5.1670e-04 - val_potential_mae: 0.0162 - val_potential_mse: 5.0603e-04 - learning_rate: 1.2906e-05
Epoch 126/1000

Epoch 126: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.3352e-04 - delta_h_mae: 0.0086 - delta_h_mse: 1.3377e-04 - loss: 0.0021 - potential_loss: 0.0019 - potential_mae: 0.0286 - potential_mse: 0.0019 - val_delta_h_loss: 9.5543e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.5459e-05 - val_loss: 0.0017 - val_potential_loss: 7.4630e-04 - val_potential_mae: 0.0224 - val_potential_mse: 7.4199e-04 - learning_rate: 1.2906e-05
Epoch 127/1000

Epoch 127: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.4261e-04 - delta_h_mae: 0.0088 - delta_h_mse: 1.4278e-04 - loss: 0.0020 - potential_loss: 0.0015 - potential_mae: 0.0257 - potential_mse: 0.0015 - val_delta_h_loss: 9.8686e-05 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 9.8407e-05 - val_loss: 0.0017 - val_potential_loss: 8.6165e-04 - val_potential_mae: 0.0225 - val_potential_mse: 8.5115e-04 - learning_rate: 1.2906e-05
Epoch 128/1000

Epoch 128: val_loss did not improve from 0.00161
231/231 - 1s - 3ms/step - delta_h_loss: 1.5740e-04 - delta_h_mae: 0.0088 - delta_h_mse: 1.5744e-04 - loss: 0.0020 - potential_loss: 0.0015 - potential_mae: 0.0271 - potential_mse: 0.0015 - val_delta_h_loss: 1.1841e-04 - val_delta_h_mae: 0.0082 - val_delta_h_mse: 1.1864e-04 - val_loss: 0.0016 - val_potential_loss: 4.6933e-04 - val_potential_mae: 0.0166 - val_potential_mse: 4.6618e-04 - learning_rate: 1.2906e-05
Epoch 129/1000

Epoch 129: ReduceLROnPlateau reducing learning rate to 6.4529103838140145e-06.

Epoch 129: val_loss improved from 0.00161 to 0.00160, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.4343e-04 - delta_h_mae: 0.0087 - delta_h_mse: 1.4318e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0271 - potential_mse: 0.0017 - val_delta_h_loss: 9.4528e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.4621e-05 - val_loss: 0.0016 - val_potential_loss: 4.4780e-04 - val_potential_mae: 0.0161 - val_potential_mse: 4.4319e-04 - learning_rate: 1.2906e-05
Epoch 130/1000

Epoch 130: val_loss improved from 0.00160 to 0.00154, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.2622e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.2641e-04 - loss: 0.0020 - potential_loss: 0.0017 - potential_mae: 0.0263 - potential_mse: 0.0017 - val_delta_h_loss: 1.0200e-04 - val_delta_h_mae: 0.0077 - val_delta_h_mse: 1.0193e-04 - val_loss: 0.0015 - val_potential_loss: 3.8825e-04 - val_potential_mae: 0.0145 - val_potential_mse: 3.8206e-04 - learning_rate: 6.4529e-06
Epoch 131/1000

Epoch 131: val_loss did not improve from 0.00154
231/231 - 1s - 3ms/step - delta_h_loss: 1.2641e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.2526e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0270 - potential_mse: 0.0018 - val_delta_h_loss: 1.1835e-04 - val_delta_h_mae: 0.0082 - val_delta_h_mse: 1.1781e-04 - val_loss: 0.0016 - val_potential_loss: 6.8418e-04 - val_potential_mae: 0.0201 - val_potential_mse: 6.7421e-04 - learning_rate: 6.4529e-06
Epoch 132/1000

Epoch 132: val_loss did not improve from 0.00154
231/231 - 1s - 3ms/step - delta_h_loss: 1.2422e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.2435e-04 - loss: 0.0019 - potential_loss: 0.0015 - potential_mae: 0.0261 - potential_mse: 0.0015 - val_delta_h_loss: 9.4414e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.4321e-05 - val_loss: 0.0016 - val_potential_loss: 4.7714e-04 - val_potential_mae: 0.0154 - val_potential_mse: 4.6642e-04 - learning_rate: 6.4529e-06
Epoch 133/1000

Epoch 133: val_loss did not improve from 0.00154
231/231 - 1s - 3ms/step - delta_h_loss: 1.2902e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.2877e-04 - loss: 0.0020 - potential_loss: 0.0019 - potential_mae: 0.0275 - potential_mse: 0.0019 - val_delta_h_loss: 9.5754e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.5655e-05 - val_loss: 0.0015 - val_potential_loss: 4.3938e-04 - val_potential_mae: 0.0147 - val_potential_mse: 4.2928e-04 - learning_rate: 6.4529e-06
Epoch 134/1000

Epoch 134: val_loss improved from 0.00154 to 0.00152, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.2573e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.2530e-04 - loss: 0.0019 - potential_loss: 0.0015 - potential_mae: 0.0265 - potential_mse: 0.0015 - val_delta_h_loss: 9.4445e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.4534e-05 - val_loss: 0.0015 - val_potential_loss: 3.6580e-04 - val_potential_mae: 0.0137 - val_potential_mse: 3.5864e-04 - learning_rate: 6.4529e-06
Epoch 135/1000

Epoch 135: val_loss did not improve from 0.00152
231/231 - 1s - 3ms/step - delta_h_loss: 1.5061e-04 - delta_h_mae: 0.0084 - delta_h_mse: 1.5077e-04 - loss: 0.0019 - potential_loss: 0.0013 - potential_mae: 0.0255 - potential_mse: 0.0013 - val_delta_h_loss: 1.1745e-04 - val_delta_h_mae: 0.0083 - val_delta_h_mse: 1.1790e-04 - val_loss: 0.0017 - val_potential_loss: 7.1358e-04 - val_potential_mae: 0.0207 - val_potential_mse: 7.1371e-04 - learning_rate: 6.4529e-06
Epoch 136/1000

Epoch 136: val_loss did not improve from 0.00152
231/231 - 1s - 3ms/step - delta_h_loss: 1.3514e-04 - delta_h_mae: 0.0084 - delta_h_mse: 1.3496e-04 - loss: 0.0020 - potential_loss: 0.0020 - potential_mae: 0.0256 - potential_mse: 0.0017 - val_delta_h_loss: 9.7101e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.6905e-05 - val_loss: 0.0016 - val_potential_loss: 6.3878e-04 - val_potential_mae: 0.0204 - val_potential_mse: 6.3333e-04 - learning_rate: 6.4529e-06
Epoch 137/1000

Epoch 137: val_loss did not improve from 0.00152
231/231 - 1s - 3ms/step - delta_h_loss: 1.2177e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.2183e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0272 - potential_mse: 0.0016 - val_delta_h_loss: 1.0413e-04 - val_delta_h_mae: 0.0077 - val_delta_h_mse: 1.0412e-04 - val_loss: 0.0015 - val_potential_loss: 4.4887e-04 - val_potential_mae: 0.0147 - val_potential_mse: 4.3817e-04 - learning_rate: 6.4529e-06
Epoch 138/1000

Epoch 138: val_loss did not improve from 0.00152
231/231 - 1s - 2ms/step - delta_h_loss: 1.4787e-04 - delta_h_mae: 0.0084 - delta_h_mse: 1.4809e-04 - loss: 0.0022 - potential_loss: 0.0022 - potential_mae: 0.0292 - potential_mse: 0.0022 - val_delta_h_loss: 9.7980e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.8010e-05 - val_loss: 0.0016 - val_potential_loss: 6.6844e-04 - val_potential_mae: 0.0198 - val_potential_mse: 6.6586e-04 - learning_rate: 6.4529e-06
Epoch 139/1000

Epoch 139: ReduceLROnPlateau reducing learning rate to 3.2264551919070072e-06.

Epoch 139: val_loss did not improve from 0.00152
231/231 - 1s - 3ms/step - delta_h_loss: 1.3207e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3203e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0265 - potential_mse: 0.0016 - val_delta_h_loss: 1.0020e-04 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 9.9963e-05 - val_loss: 0.0016 - val_potential_loss: 4.4800e-04 - val_potential_mae: 0.0157 - val_potential_mse: 4.4198e-04 - learning_rate: 6.4529e-06
Epoch 140/1000

Epoch 140: val_loss did not improve from 0.00152
231/231 - 1s - 3ms/step - delta_h_loss: 1.2662e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.2689e-04 - loss: 0.0019 - potential_loss: 0.0015 - potential_mae: 0.0259 - potential_mse: 0.0015 - val_delta_h_loss: 1.0185e-04 - val_delta_h_mae: 0.0076 - val_delta_h_mse: 1.0172e-04 - val_loss: 0.0016 - val_potential_loss: 5.6609e-04 - val_potential_mae: 0.0189 - val_potential_mse: 5.6159e-04 - learning_rate: 3.2265e-06
Epoch 141/1000

Epoch 141: val_loss improved from 0.00152 to 0.00152, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.2481e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.2490e-04 - loss: 0.0020 - potential_loss: 0.0017 - potential_mae: 0.0261 - potential_mse: 0.0017 - val_delta_h_loss: 1.0876e-04 - val_delta_h_mae: 0.0079 - val_delta_h_mse: 1.0910e-04 - val_loss: 0.0015 - val_potential_loss: 4.1842e-04 - val_potential_mae: 0.0149 - val_potential_mse: 4.1064e-04 - learning_rate: 3.2265e-06
Epoch 142/1000

Epoch 142: val_loss improved from 0.00152 to 0.00151, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.3430e-04 - delta_h_mae: 0.0084 - delta_h_mse: 1.3414e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0265 - potential_mse: 0.0016 - val_delta_h_loss: 1.1208e-04 - val_delta_h_mae: 0.0079 - val_delta_h_mse: 1.1173e-04 - val_loss: 0.0015 - val_potential_loss: 3.9193e-04 - val_potential_mae: 0.0143 - val_potential_mse: 3.8477e-04 - learning_rate: 3.2265e-06
Epoch 143/1000

Epoch 143: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.3480e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.3481e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0274 - potential_mse: 0.0018 - val_delta_h_loss: 9.4633e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.4569e-05 - val_loss: 0.0016 - val_potential_loss: 5.1936e-04 - val_potential_mae: 0.0178 - val_potential_mse: 5.1292e-04 - learning_rate: 3.2265e-06
Epoch 144/1000

Epoch 144: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.3592e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3620e-04 - loss: 0.0021 - potential_loss: 0.0023 - potential_mae: 0.0297 - potential_mse: 0.0022 - val_delta_h_loss: 9.8489e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8310e-05 - val_loss: 0.0016 - val_potential_loss: 6.4615e-04 - val_potential_mae: 0.0210 - val_potential_mse: 6.4144e-04 - learning_rate: 3.2265e-06
Epoch 145/1000

Epoch 145: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.3668e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.3660e-04 - loss: 0.0020 - potential_loss: 0.0019 - potential_mae: 0.0278 - potential_mse: 0.0018 - val_delta_h_loss: 9.8652e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8860e-05 - val_loss: 0.0016 - val_potential_loss: 5.5091e-04 - val_potential_mae: 0.0171 - val_potential_mse: 5.4003e-04 - learning_rate: 3.2265e-06
Epoch 146/1000

Epoch 146: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.6556e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.5740e-04 - loss: 0.0022 - potential_loss: 0.0029 - potential_mae: 0.0292 - potential_mse: 0.0023 - val_delta_h_loss: 9.4488e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.4392e-05 - val_loss: 0.0016 - val_potential_loss: 6.0997e-04 - val_potential_mae: 0.0195 - val_potential_mse: 6.0641e-04 - learning_rate: 3.2265e-06
Epoch 147/1000

Epoch 147: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.3049e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3040e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0263 - potential_mse: 0.0016 - val_delta_h_loss: 1.0803e-04 - val_delta_h_mae: 0.0078 - val_delta_h_mse: 1.0776e-04 - val_loss: 0.0015 - val_potential_loss: 4.6353e-04 - val_potential_mae: 0.0161 - val_potential_mse: 4.5678e-04 - learning_rate: 3.2265e-06
Epoch 148/1000

Epoch 148: val_loss did not improve from 0.00151
231/231 - 1s - 3ms/step - delta_h_loss: 1.7154e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.7177e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0267 - potential_mse: 0.0016 - val_delta_h_loss: 1.0912e-04 - val_delta_h_mae: 0.0078 - val_delta_h_mse: 1.0884e-04 - val_loss: 0.0016 - val_potential_loss: 6.3293e-04 - val_potential_mae: 0.0204 - val_potential_mse: 6.2788e-04 - learning_rate: 3.2265e-06
Epoch 149/1000

Epoch 149: val_loss improved from 0.00151 to 0.00150, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.2693e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.2702e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0274 - potential_mse: 0.0015 - val_delta_h_loss: 9.7719e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.7603e-05 - val_loss: 0.0015 - val_potential_loss: 3.8080e-04 - val_potential_mae: 0.0142 - val_potential_mse: 3.7429e-04 - learning_rate: 3.2265e-06
Epoch 150/1000

Epoch 150: val_loss did not improve from 0.00150
231/231 - 1s - 3ms/step - delta_h_loss: 1.3688e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3722e-04 - loss: 0.0019 - potential_loss: 0.0015 - potential_mae: 0.0267 - potential_mse: 0.0014 - val_delta_h_loss: 1.0364e-04 - val_delta_h_mae: 0.0076 - val_delta_h_mse: 1.0394e-04 - val_loss: 0.0015 - val_potential_loss: 4.0991e-04 - val_potential_mae: 0.0146 - val_potential_mse: 4.0230e-04 - learning_rate: 3.2265e-06
Epoch 151/1000

Epoch 151: val_loss improved from 0.00150 to 0.00148, saving model to best_gravity_model.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

231/231 - 1s - 3ms/step - delta_h_loss: 1.2645e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.2670e-04 - loss: 0.0018 - potential_loss: 0.0012 - potential_mae: 0.0241 - potential_mse: 0.0012 - val_delta_h_loss: 9.9038e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8995e-05 - val_loss: 0.0015 - val_potential_loss: 3.7225e-04 - val_potential_mae: 0.0138 - val_potential_mse: 3.6471e-04 - learning_rate: 3.2265e-06
Epoch 152/1000
Epoch 152/1000

Epoch 152: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.1862e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.1883e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0276 - potential_mse: 0.0018 - val_delta_h_loss: 1.0446e-04 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 1.0466e-04 - val_loss: 0.0015 - val_potential_loss: 4.9258e-04 - val_potential_mae: 0.0169 - val_potential_mse: 4.8477e-04 - learning_rate: 3.2265e-06
Epoch 153/1000

Epoch 153: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.3094e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.3083e-04 - loss: 0.0020 - potential_loss: 0.0019 - potential_mae: 0.0280 - potential_mse: 0.0019 - val_delta_h_loss: 1.0752e-04 - val_delta_h_mae: 0.0076 - val_delta_h_mse: 1.0744e-04 - val_loss: 0.0016 - val_potential_loss: 5.9781e-04 - val_potential_mae: 0.0198 - val_potential_mse: 5.9493e-04 - learning_rate: 3.2265e-06
Epoch 154/1000

Epoch 154: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.3766e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3759e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0270 - potential_mse: 0.0018 - val_delta_h_loss: 1.0335e-04 - val_delta_h_mae: 0.0076 - val_delta_h_mse: 1.0319e-04 - val_loss: 0.0015 - val_potential_loss: 5.0595e-04 - val_potential_mae: 0.0171 - val_potential_mse: 4.9790e-04 - learning_rate: 3.2265e-06
Epoch 155/1000

Epoch 155: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.1870e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.1821e-04 - loss: 0.0018 - potential_loss: 0.0014 - potential_mae: 0.0256 - potential_mse: 0.0013 - val_delta_h_loss: 9.8646e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8765e-05 - val_loss: 0.0015 - val_potential_loss: 3.9107e-04 - val_potential_mae: 0.0143 - val_potential_mse: 3.8409e-04 - learning_rate: 3.2265e-06
Epoch 156/1000

Epoch 156: val_loss did not improve from 0.00148
231/231 - 1s - 2ms/step - delta_h_loss: 1.3836e-04 - delta_h_mae: 0.0083 - delta_h_mse: 1.3832e-04 - loss: 0.0021 - potential_loss: 0.0023 - potential_mae: 0.0299 - potential_mse: 0.0023 - val_delta_h_loss: 9.8141e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.8157e-05 - val_loss: 0.0016 - val_potential_loss: 5.8778e-04 - val_potential_mae: 0.0197 - val_potential_mse: 5.8209e-04 - learning_rate: 3.2265e-06
Epoch 157/1000

Epoch 157: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2397e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2381e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0275 - potential_mse: 0.0018 - val_delta_h_loss: 1.1808e-04 - val_delta_h_mae: 0.0082 - val_delta_h_mse: 1.1854e-04 - val_loss: 0.0015 - val_potential_loss: 4.8460e-04 - val_potential_mae: 0.0173 - val_potential_mse: 4.8008e-04 - learning_rate: 3.2265e-06
Epoch 158/1000

Epoch 158: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.4512e-04 - delta_h_mae: 0.0084 - delta_h_mse: 1.4541e-04 - loss: 0.0021 - potential_loss: 0.0021 - potential_mae: 0.0293 - potential_mse: 0.0021 - val_delta_h_loss: 1.0458e-04 - val_delta_h_mae: 0.0077 - val_delta_h_mse: 1.0477e-04 - val_loss: 0.0016 - val_potential_loss: 7.1952e-04 - val_potential_mae: 0.0221 - val_potential_mse: 7.1469e-04 - learning_rate: 3.2265e-06
Epoch 159/1000

Epoch 159: ReduceLROnPlateau reducing learning rate to 1.6132275959535036e-06.

Epoch 159: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.5060e-04 - delta_h_mae: 0.0085 - delta_h_mse: 1.5071e-04 - loss: 0.0019 - potential_loss: 0.0015 - potential_mae: 0.0271 - potential_mse: 0.0015 - val_delta_h_loss: 9.6247e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.6082e-05 - val_loss: 0.0015 - val_potential_loss: 4.6013e-04 - val_potential_mae: 0.0163 - val_potential_mse: 4.5592e-04 - learning_rate: 3.2265e-06
Epoch 160/1000

Epoch 160: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.4029e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.4035e-04 - loss: 0.0020 - potential_loss: 0.0020 - potential_mae: 0.0286 - potential_mse: 0.0020 - val_delta_h_loss: 9.7170e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.7076e-05 - val_loss: 0.0015 - val_potential_loss: 4.6355e-04 - val_potential_mae: 0.0163 - val_potential_mse: 4.5669e-04 - learning_rate: 1.6132e-06
Epoch 161/1000

Epoch 161: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2227e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.2223e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0262 - potential_mse: 0.0016 - val_delta_h_loss: 1.0006e-04 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 9.9942e-05 - val_loss: 0.0015 - val_potential_loss: 4.5908e-04 - val_potential_mae: 0.0166 - val_potential_mse: 4.5379e-04 - learning_rate: 1.6132e-06
Epoch 162/1000

Epoch 162: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2341e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2359e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0269 - potential_mse: 0.0016 - val_delta_h_loss: 9.4898e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.5009e-05 - val_loss: 0.0015 - val_potential_loss: 4.5705e-04 - val_potential_mae: 0.0160 - val_potential_mse: 4.4983e-04 - learning_rate: 1.6132e-06
Epoch 163/1000

Epoch 163: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2242e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2264e-04 - loss: 0.0018 - potential_loss: 0.0013 - potential_mae: 0.0252 - potential_mse: 0.0013 - val_delta_h_loss: 9.4332e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.4387e-05 - val_loss: 0.0015 - val_potential_loss: 4.8861e-04 - val_potential_mae: 0.0167 - val_potential_mse: 4.8071e-04 - learning_rate: 1.6132e-06
Epoch 164/1000

Epoch 164: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2197e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2207e-04 - loss: 0.0020 - potential_loss: 0.0018 - potential_mae: 0.0274 - potential_mse: 0.0018 - val_delta_h_loss: 9.7520e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.7521e-05 - val_loss: 0.0015 - val_potential_loss: 5.5837e-04 - val_potential_mae: 0.0184 - val_potential_mse: 5.5270e-04 - learning_rate: 1.6132e-06
Epoch 165/1000

Epoch 165: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2889e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2859e-04 - loss: 0.0020 - potential_loss: 0.0019 - potential_mae: 0.0270 - potential_mse: 0.0018 - val_delta_h_loss: 9.9535e-05 - val_delta_h_mae: 0.0075 - val_delta_h_mse: 9.9765e-05 - val_loss: 0.0015 - val_potential_loss: 4.2670e-04 - val_potential_mae: 0.0153 - val_potential_mse: 4.2048e-04 - learning_rate: 1.6132e-06
Epoch 166/1000

Epoch 166: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2694e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2697e-04 - loss: 0.0018 - potential_loss: 0.0014 - potential_mae: 0.0252 - potential_mse: 0.0014 - val_delta_h_loss: 9.5808e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.5671e-05 - val_loss: 0.0015 - val_potential_loss: 4.3310e-04 - val_potential_mae: 0.0153 - val_potential_mse: 4.2596e-04 - learning_rate: 1.6132e-06
Epoch 167/1000

Epoch 167: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.3804e-04 - delta_h_mae: 0.0082 - delta_h_mse: 1.3802e-04 - loss: 0.0018 - potential_loss: 0.0015 - potential_mae: 0.0265 - potential_mse: 0.0014 - val_delta_h_loss: 9.7105e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.7210e-05 - val_loss: 0.0015 - val_potential_loss: 5.0000e-04 - val_potential_mae: 0.0173 - val_potential_mse: 4.9541e-04 - learning_rate: 1.6132e-06
Epoch 168/1000

Epoch 168: val_loss did not improve from 0.00148
231/231 - 1s - 2ms/step - delta_h_loss: 1.9695e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.4756e-04 - loss: 0.0022 - potential_loss: 0.0027 - potential_mae: 0.0290 - potential_mse: 0.0024 - val_delta_h_loss: 9.5317e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.5291e-05 - val_loss: 0.0015 - val_potential_loss: 6.0180e-04 - val_potential_mae: 0.0200 - val_potential_mse: 5.9651e-04 - learning_rate: 1.6132e-06
Epoch 169/1000

Epoch 169: ReduceLROnPlateau reducing learning rate to 8.066137979767518e-07.

Epoch 169: val_loss did not improve from 0.00148
231/231 - 1s - 2ms/step - delta_h_loss: 1.3234e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.3254e-04 - loss: 0.0020 - potential_loss: 0.0020 - potential_mae: 0.0274 - potential_mse: 0.0020 - val_delta_h_loss: 1.0106e-04 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 1.0118e-04 - val_loss: 0.0016 - val_potential_loss: 6.2762e-04 - val_potential_mae: 0.0203 - val_potential_mse: 6.2146e-04 - learning_rate: 1.6132e-06
Epoch 170/1000

Epoch 170: val_loss did not improve from 0.00148
231/231 - 1s - 2ms/step - delta_h_loss: 1.2688e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2680e-04 - loss: 0.0019 - potential_loss: 0.0016 - potential_mae: 0.0260 - potential_mse: 0.0016 - val_delta_h_loss: 9.8268e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8147e-05 - val_loss: 0.0015 - val_potential_loss: 4.7606e-04 - val_potential_mae: 0.0161 - val_potential_mse: 4.6740e-04 - learning_rate: 8.0661e-07
Epoch 171/1000

Epoch 171: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2397e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2421e-04 - loss: 0.0019 - potential_loss: 0.0018 - potential_mae: 0.0277 - potential_mse: 0.0018 - val_delta_h_loss: 9.8678e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8619e-05 - val_loss: 0.0015 - val_potential_loss: 5.2943e-04 - val_potential_mae: 0.0181 - val_potential_mse: 5.2372e-04 - learning_rate: 8.0661e-07
Epoch 172/1000

Epoch 172: val_loss did not improve from 0.00148
231/231 - 1s - 3ms/step - delta_h_loss: 1.2145e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2123e-04 - loss: 0.0020 - potential_loss: 0.0019 - potential_mae: 0.0277 - potential_mse: 0.0018 - val_delta_h_loss: 9.8957e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.8915e-05 - val_loss: 0.0015 - val_potential_loss: 5.4999e-04 - val_potential_mae: 0.0182 - val_potential_mse: 5.4270e-04 - learning_rate: 8.0661e-07
Epoch 173/1000

Epoch 173: val_loss did not improve from 0.00148
231/231 - 1s - 4ms/step - delta_h_loss: 1.2531e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2509e-04 - loss: 0.0019 - potential_loss: 0.0017 - potential_mae: 0.0274 - potential_mse: 0.0017 - val_delta_h_loss: 9.5576e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.5674e-05 - val_loss: 0.0015 - val_potential_loss: 4.8466e-04 - val_potential_mae: 0.0166 - val_potential_mse: 4.7703e-04 - learning_rate: 8.0661e-07
Epoch 174/1000

Epoch 174: val_loss did not improve from 0.00148
231/231 - 1s - 5ms/step - delta_h_loss: 1.2528e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2477e-04 - loss: 0.0019 - potential_loss: 0.0019 - potential_mae: 0.0282 - potential_mse: 0.0018 - val_delta_h_loss: 9.7309e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.7273e-05 - val_loss: 0.0016 - val_potential_loss: 6.7312e-04 - val_potential_mae: 0.0214 - val_potential_mse: 6.6933e-04 - learning_rate: 8.0661e-07
Epoch 175/1000

Epoch 175: val_loss did not improve from 0.00148
231/231 - 2s - 7ms/step - delta_h_loss: 1.2860e-04 - delta_h_mae: 0.0080 - delta_h_mse: 1.2801e-04 - loss: 0.0020 - potential_loss: 0.0020 - potential_mae: 0.0269 - potential_mse: 0.0018 - val_delta_h_loss: 9.6640e-05 - val_delta_h_mae: 0.0073 - val_delta_h_mse: 9.6712e-05 - val_loss: 0.0016 - val_potential_loss: 7.1996e-04 - val_potential_mae: 0.0220 - val_potential_mse: 7.1368e-04 - learning_rate: 8.0661e-07
Epoch 176/1000

Epoch 176: val_loss did not improve from 0.00148
231/231 - 1s - 6ms/step - delta_h_loss: 1.3672e-04 - delta_h_mae: 0.0081 - delta_h_mse: 1.3601e-04 - loss: 0.0020 - potential_loss: 0.0020 - potential_mae: 0.0285 - potential_mse: 0.0020 - val_delta_h_loss: 9.7850e-05 - val_delta_h_mae: 0.0074 - val_delta_h_mse: 9.7922e-05 - val_loss: 0.0015 - val_potential_loss: 5.7965e-04 - val_potential_mae: 0.0194 - val_potential_mse: 5.7386e-04 - learning_rate: 8.0661e-07
Epoch 176: early stopping
Restoring model weights from the end of the best epoch: 151.

In [75]:
y_pred = best_model.predict(X_test)
phi_pred, dh_pred = y_pred[0], y_pred[1]

# Для денормализации нужно создать массив правильной формы
phi_pred_2d = np.column_stack((phi_pred, np.zeros_like(phi_pred)))
dh_pred_2d = np.column_stack((np.zeros_like(dh_pred), dh_pred))

phi_original = scaler_y.inverse_transform(phi_pred_2d)[:, 0]
dh_original = scaler_y.inverse_transform(dh_pred_2d)[:, 1]

print("Пример предсказаний:")
print("Потенциал (φ):", phi_original[:5])
print("Аномалия высоты (Δh):", dh_original[:5])

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Пример предсказаний:
Потенциал (φ): [62373644. 62359488. 62388392. 62393080. 62381264.]
Аномалия высоты (Δh): [-2248.4272 -2648.6873 -1463.2955 -1184.2635 -1795.5895]

In [76]:
from plotly.offline import init_notebook_mode, plot
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
from scipy.interpolate import griddata

# Инициализация
init_notebook_mode(connected=True)

# Подготовка данных
# Предсказанные значения (уже есть)
phi_pred = y_pred[0].flatten()
dh_pred = y_pred[1].flatten()

# Тестовые значения
phi_test = y_test[:, 0].flatten()
dh_test = y_test[:, 1].flatten()

# Денормализация тестовых значений
phi_test_2d = np.column_stack((phi_test, np.zeros_like(phi_test)))
dh_test_2d = np.column_stack((np.zeros_like(dh_test), dh_test))

phi_test_original = scaler_y.inverse_transform(phi_test_2d)[:, 0]
dh_test_original = scaler_y.inverse_transform(dh_test_2d)[:, 1]

# Разницы между предсказаниями и тестом
phi_diff = phi_original - phi_test_original
dh_diff = dh_original - dh_test_original

# Координаты для всех графиков
longitudes = X_test[:, 1].flatten()
latitudes = X_test[:, 0].flatten()

# Функция для создания поверхности
def create_surface(x, y, z, title, colorscale='Viridis'):
    mask = ~np.isnan(x) & ~np.isnan(y) & ~np.isnan(z)
    x, y, z = x[mask], y[mask], z[mask]
    
    grid_x, grid_y = np.mgrid[
        np.min(x):np.max(x):100j,
        np.min(y):np.max(y):100j
    ]
    
    try:
        grid_z = griddata(
            (x, y), z, (grid_x, grid_y), 
            method='cubic', fill_value=np.nanmean(z))
    except:
        grid_z = griddata(
            (x, y), z, (grid_x, grid_y), 
            method='linear', fill_value=np.nanmean(z))
    
    return go.Surface(
        x=grid_x, y=grid_y, z=grid_z,
        colorscale=colorscale, opacity=0.8,
        surfacecolor=grid_z, name=title
    )

# Создаем фигуру с 6 субплогами (2 ряда по 3 колонки)
fig = make_subplots(
    rows=2, cols=3,
    specs=[[{'type': 'surface'}, {'type': 'surface'}, {'type': 'surface'}],
           [{'type': 'surface'}, {'type': 'surface'}, {'type': 'surface'}]],
    subplot_titles=(
        'Предсказанный потенциал', 'Тестовый потенциал', 'Разность потенциалов',
        'Предсказанная аномалия', 'Тестовая аномалия', 'Разность аномалий'
    ),
    horizontal_spacing=0.05,
    vertical_spacing=0.1
)

# Верхний ряд: потенциал
fig.add_trace(
    create_surface(longitudes, latitudes, phi_original, 'Предсказанный потенциал'),
    row=1, col=1
)
fig.add_trace(
    create_surface(longitudes, latitudes, phi_test_original, 'Тестовый потенциал'),
    row=1, col=2
)
fig.add_trace(
    create_surface(longitudes, latitudes, phi_diff, 'Разность потенциалов', 'RdBu'),
    row=1, col=3
)

# Нижний ряд: аномалия высоты
fig.add_trace(
    create_surface(longitudes, latitudes, dh_original, 'Предсказанная аномалия'),
    row=2, col=1
)
fig.add_trace(
    create_surface(longitudes, latitudes, dh_test_original, 'Тестовая аномалия'),
    row=2, col=2
)
fig.add_trace(
    create_surface(longitudes, latitudes, dh_diff, 'Разность аномалий', 'RdBu'),
    row=2, col=3
)

# Настройки макета
fig.update_layout(
    title_text='3D визуализация гравитационного поля: предсказания, тест и разности',
    scene=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Потенциал (м²/с²)'
    ),
    scene2=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Потенциал (м²/с²)'
    ),
    scene3=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Разность (м²/с²)'
    ),
    scene4=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Аномалия (м)'
    ),
    scene5=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Аномалия (м)'
    ),
    scene6=dict(
        xaxis_title='Долгота',
        yaxis_title='Широта',
        zaxis_title='Разность (м)'
    ),
    width=1700,
    height=1100,
    margin=dict(r=50, l=50, b=50, t=50)
)

# Сохраняем и отображаем
plot(fig, filename='gravity_field_comparison.html', auto_open=False)
fig.show()

In [77]:
pd.DataFrame(dh_diff).describe().T\
            .style.bar(subset=['mean'], color=px.colors.qualitative.G10[1])\
            .background_gradient(subset=['std'])\
            .background_gradient(subset=['50%'],)

In [78]:
pd.DataFrame(phi_diff).describe().T\
            .style.bar(subset=['mean'], color=px.colors.qualitative.G10[1])\
            .background_gradient(subset=['std'])\
            .background_gradient(subset=['50%'],)

In [79]:
best_model.save("colorado600.keras")  # Один файл (аналог .h5, но современный)

In [84]:
best_model.save_weights("model_weights_colorado600.weights.h5")  # .h5 или .weights.h5